version: '3.8'
services:
  php-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: php-sdk-tests
    environment:
      # Проброс переменных из .env на хосте внутрь контейнера
      API_HOST: ''
      API_LOGIN: ''
      API_PASSWORD: ''
    # Монтируем локальную директорию с кодом в /app контейнера
    volumes:
      - .:/app
    command: sh -c "composer install --no-interaction && composer test"

    # тесты запускать командой docker compose -f docker-compose.test.yml up --build и не забыть поменять в файле API_HOST, API_LOGIN, API_PASSWORD на актуальные