<?php
/**
 * CompanySettings
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * МойСклад JSON API
 *
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CompanySettings Class Doc Comment
 *
 * @category Class
 * @description Настройки компании (companysettings)
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CompanySettings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CompanySettings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'meta' => '\OpenAPI\Client\Model\Meta',
        'currency' => '\OpenAPI\Client\Model\Currency',
        'price_types' => '\OpenAPI\Client\Model\PriceType[]',
        'discount_strategy' => 'string',
        'global_operation_numbering' => 'bool',
        'check_shipping_stock' => 'bool',
        'check_min_price' => 'bool',
        'use_recycle_bin' => 'bool',
        'use_company_address' => 'bool',
        'company_address' => 'string',
        'account_country' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'meta' => null,
        'currency' => null,
        'price_types' => null,
        'discount_strategy' => null,
        'global_operation_numbering' => null,
        'check_shipping_stock' => null,
        'check_min_price' => null,
        'use_recycle_bin' => null,
        'use_company_address' => null,
        'company_address' => null,
        'account_country' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'meta' => false,
        'currency' => false,
        'price_types' => false,
        'discount_strategy' => false,
        'global_operation_numbering' => false,
        'check_shipping_stock' => false,
        'check_min_price' => false,
        'use_recycle_bin' => false,
        'use_company_address' => false,
        'company_address' => false,
        'account_country' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'meta' => 'meta',
        'currency' => 'currency',
        'price_types' => 'priceTypes',
        'discount_strategy' => 'discountStrategy',
        'global_operation_numbering' => 'globalOperationNumbering',
        'check_shipping_stock' => 'checkShippingStock',
        'check_min_price' => 'checkMinPrice',
        'use_recycle_bin' => 'useRecycleBin',
        'use_company_address' => 'useCompanyAddress',
        'company_address' => 'companyAddress',
        'account_country' => 'accountCountry'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'meta' => 'setMeta',
        'currency' => 'setCurrency',
        'price_types' => 'setPriceTypes',
        'discount_strategy' => 'setDiscountStrategy',
        'global_operation_numbering' => 'setGlobalOperationNumbering',
        'check_shipping_stock' => 'setCheckShippingStock',
        'check_min_price' => 'setCheckMinPrice',
        'use_recycle_bin' => 'setUseRecycleBin',
        'use_company_address' => 'setUseCompanyAddress',
        'company_address' => 'setCompanyAddress',
        'account_country' => 'setAccountCountry'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'meta' => 'getMeta',
        'currency' => 'getCurrency',
        'price_types' => 'getPriceTypes',
        'discount_strategy' => 'getDiscountStrategy',
        'global_operation_numbering' => 'getGlobalOperationNumbering',
        'check_shipping_stock' => 'getCheckShippingStock',
        'check_min_price' => 'getCheckMinPrice',
        'use_recycle_bin' => 'getUseRecycleBin',
        'use_company_address' => 'getUseCompanyAddress',
        'company_address' => 'getCompanyAddress',
        'account_country' => 'getAccountCountry'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DISCOUNT_STRATEGY_BY_SUM = 'bySum';
    public const DISCOUNT_STRATEGY_BY_PRIORITY = 'byPriority';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDiscountStrategyAllowableValues()
    {
        return [
            self::DISCOUNT_STRATEGY_BY_SUM,
            self::DISCOUNT_STRATEGY_BY_PRIORITY,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('meta', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('price_types', $data ?? [], null);
        $this->setIfExists('discount_strategy', $data ?? [], null);
        $this->setIfExists('global_operation_numbering', $data ?? [], null);
        $this->setIfExists('check_shipping_stock', $data ?? [], null);
        $this->setIfExists('check_min_price', $data ?? [], null);
        $this->setIfExists('use_recycle_bin', $data ?? [], null);
        $this->setIfExists('use_company_address', $data ?? [], null);
        $this->setIfExists('company_address', $data ?? [], null);
        $this->setIfExists('account_country', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getDiscountStrategyAllowableValues();
        if (!is_null($this->container['discount_strategy']) && !in_array($this->container['discount_strategy'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'discount_strategy', must be one of '%s'",
                $this->container['discount_strategy'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['company_address']) && (mb_strlen($this->container['company_address']) > 255)) {
            $invalidProperties[] = "invalid value for 'company_address', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['account_country']) && (mb_strlen($this->container['account_country']) > 255)) {
            $invalidProperties[] = "invalid value for 'account_country', the character length must be smaller than or equal to 255.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets meta
     *
     * @return \OpenAPI\Client\Model\Meta|null
     */
    public function getMeta()
    {
        return $this->container['meta'];
    }

    /**
     * Sets meta
     *
     * @param \OpenAPI\Client\Model\Meta|null $meta meta
     *
     * @return self
     */
    public function setMeta($meta)
    {
        if (is_null($meta)) {
            throw new \InvalidArgumentException('non-nullable meta cannot be null');
        }
        $this->container['meta'] = $meta;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return \OpenAPI\Client\Model\Currency|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param \OpenAPI\Client\Model\Currency|null $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets price_types
     *
     * @return \OpenAPI\Client\Model\PriceType[]|null
     */
    public function getPriceTypes()
    {
        return $this->container['price_types'];
    }

    /**
     * Sets price_types
     *
     * @param \OpenAPI\Client\Model\PriceType[]|null $price_types Коллекция всех существующих типов цен
     *
     * @return self
     */
    public function setPriceTypes($price_types)
    {
        if (is_null($price_types)) {
            throw new \InvalidArgumentException('non-nullable price_types cannot be null');
        }
        $this->container['price_types'] = $price_types;

        return $this;
    }

    /**
     * Gets discount_strategy
     *
     * @return string|null
     */
    public function getDiscountStrategy()
    {
        return $this->container['discount_strategy'];
    }

    /**
     * Sets discount_strategy
     *
     * @param string|null $discount_strategy Совместное применение скидок
     *
     * @return self
     */
    public function setDiscountStrategy($discount_strategy)
    {
        if (is_null($discount_strategy)) {
            throw new \InvalidArgumentException('non-nullable discount_strategy cannot be null');
        }
        $allowedValues = $this->getDiscountStrategyAllowableValues();
        if (!in_array($discount_strategy, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'discount_strategy', must be one of '%s'",
                    $discount_strategy,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['discount_strategy'] = $discount_strategy;

        return $this;
    }

    /**
     * Gets global_operation_numbering
     *
     * @return bool|null
     */
    public function getGlobalOperationNumbering()
    {
        return $this->container['global_operation_numbering'];
    }

    /**
     * Sets global_operation_numbering
     *
     * @param bool|null $global_operation_numbering Использовать сквозную нумерацию документов
     *
     * @return self
     */
    public function setGlobalOperationNumbering($global_operation_numbering)
    {
        if (is_null($global_operation_numbering)) {
            throw new \InvalidArgumentException('non-nullable global_operation_numbering cannot be null');
        }
        $this->container['global_operation_numbering'] = $global_operation_numbering;

        return $this;
    }

    /**
     * Gets check_shipping_stock
     *
     * @return bool|null
     */
    public function getCheckShippingStock()
    {
        return $this->container['check_shipping_stock'];
    }

    /**
     * Sets check_shipping_stock
     *
     * @param bool|null $check_shipping_stock Запретить отгрузку отсутствующих товаров
     *
     * @return self
     */
    public function setCheckShippingStock($check_shipping_stock)
    {
        if (is_null($check_shipping_stock)) {
            throw new \InvalidArgumentException('non-nullable check_shipping_stock cannot be null');
        }
        $this->container['check_shipping_stock'] = $check_shipping_stock;

        return $this;
    }

    /**
     * Gets check_min_price
     *
     * @return bool|null
     */
    public function getCheckMinPrice()
    {
        return $this->container['check_min_price'];
    }

    /**
     * Sets check_min_price
     *
     * @param bool|null $check_min_price Автоматически устанавливать минимальную цену
     *
     * @return self
     */
    public function setCheckMinPrice($check_min_price)
    {
        if (is_null($check_min_price)) {
            throw new \InvalidArgumentException('non-nullable check_min_price cannot be null');
        }
        $this->container['check_min_price'] = $check_min_price;

        return $this;
    }

    /**
     * Gets use_recycle_bin
     *
     * @return bool|null
     */
    public function getUseRecycleBin()
    {
        return $this->container['use_recycle_bin'];
    }

    /**
     * Sets use_recycle_bin
     *
     * @param bool|null $use_recycle_bin Использовать корзину
     *
     * @return self
     */
    public function setUseRecycleBin($use_recycle_bin)
    {
        if (is_null($use_recycle_bin)) {
            throw new \InvalidArgumentException('non-nullable use_recycle_bin cannot be null');
        }
        $this->container['use_recycle_bin'] = $use_recycle_bin;

        return $this;
    }

    /**
     * Gets use_company_address
     *
     * @return bool|null
     */
    public function getUseCompanyAddress()
    {
        return $this->container['use_company_address'];
    }

    /**
     * Sets use_company_address
     *
     * @param bool|null $use_company_address Использовать адрес компании для электронных писем
     *
     * @return self
     */
    public function setUseCompanyAddress($use_company_address)
    {
        if (is_null($use_company_address)) {
            throw new \InvalidArgumentException('non-nullable use_company_address cannot be null');
        }
        $this->container['use_company_address'] = $use_company_address;

        return $this;
    }

    /**
     * Gets company_address
     *
     * @return string|null
     */
    public function getCompanyAddress()
    {
        return $this->container['company_address'];
    }

    /**
     * Sets company_address
     *
     * @param string|null $company_address Адрес компании для электронных писем
     *
     * @return self
     */
    public function setCompanyAddress($company_address)
    {
        if (is_null($company_address)) {
            throw new \InvalidArgumentException('non-nullable company_address cannot be null');
        }
        if ((mb_strlen($company_address) > 255)) {
            throw new \InvalidArgumentException('invalid length for $company_address when calling CompanySettings., must be smaller than or equal to 255.');
        }

        $this->container['company_address'] = $company_address;

        return $this;
    }

    /**
     * Gets account_country
     *
     * @return string|null
     */
    public function getAccountCountry()
    {
        return $this->container['account_country'];
    }

    /**
     * Sets account_country
     *
     * @param string|null $account_country Страновая конфигурация аккаунта
     *
     * @return self
     */
    public function setAccountCountry($account_country)
    {
        if (is_null($account_country)) {
            throw new \InvalidArgumentException('non-nullable account_country cannot be null');
        }
        if ((mb_strlen($account_country) > 255)) {
            throw new \InvalidArgumentException('invalid length for $account_country when calling CompanySettings., must be smaller than or equal to 255.');
        }

        $this->container['account_country'] = $account_country;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


