<?php
/**
 * CreateCashInBatch200ResponseInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * МойСклад JSON API
 *
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CreateCashInBatch200ResponseInner Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateCashInBatch200ResponseInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'createCashInBatch_200_response_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'meta' => '\OpenAPI\Client\Model\Meta',
        'id' => 'string',
        'account_id' => 'string',
        'applicable' => 'bool',
        'name' => 'string',
        'code' => 'string',
        'external_code' => 'string',
        'sync_id' => 'string',
        'description' => 'string',
        'created' => 'string',
        'deleted' => 'string',
        'updated' => 'string',
        'moment' => 'string',
        'attributes' => '\OpenAPI\Client\Model\AttributeAbstract[]',
        'contract' => '\OpenAPI\Client\Model\Contract',
        'files' => '\OpenAPI\Client\Model\FileList',
        'payment_purpose' => 'string',
        'printed' => 'bool',
        'project' => '\OpenAPI\Client\Model\Project',
        'published' => 'bool',
        'owner' => '\OpenAPI\Client\Model\Employee',
        'group' => '\OpenAPI\Client\Model\Group',
        'sales_channel' => '\OpenAPI\Client\Model\SalesChannel',
        'shared' => 'bool',
        'state' => '\OpenAPI\Client\Model\State',
        'rate' => '\OpenAPI\Client\Model\CurrencyRate',
        'organization' => '\OpenAPI\Client\Model\Organization',
        'agent' => '\OpenAPI\Client\Model\Counterparty',
        'sum' => 'float',
        'vat_sum' => 'float',
        'facture_out' => '\OpenAPI\Client\Model\FactureOut',
        'operations' => '\OpenAPI\Client\Model\CashInOperation[]',
        'errors' => '\OpenAPI\Client\Model\ErrorErrorsInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'meta' => null,
        'id' => 'uuid',
        'account_id' => 'uuid',
        'applicable' => null,
        'name' => null,
        'code' => null,
        'external_code' => null,
        'sync_id' => 'uuid',
        'description' => null,
        'created' => null,
        'deleted' => null,
        'updated' => null,
        'moment' => null,
        'attributes' => null,
        'contract' => null,
        'files' => null,
        'payment_purpose' => null,
        'printed' => null,
        'project' => null,
        'published' => null,
        'owner' => null,
        'group' => null,
        'sales_channel' => null,
        'shared' => null,
        'state' => null,
        'rate' => null,
        'organization' => null,
        'agent' => null,
        'sum' => 'double',
        'vat_sum' => 'double',
        'facture_out' => null,
        'operations' => null,
        'errors' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'meta' => false,
        'id' => false,
        'account_id' => false,
        'applicable' => false,
        'name' => false,
        'code' => false,
        'external_code' => false,
        'sync_id' => false,
        'description' => true,
        'created' => false,
        'deleted' => false,
        'updated' => false,
        'moment' => false,
        'attributes' => false,
        'contract' => true,
        'files' => true,
        'payment_purpose' => false,
        'printed' => false,
        'project' => true,
        'published' => false,
        'owner' => true,
        'group' => false,
        'sales_channel' => true,
        'shared' => false,
        'state' => true,
        'rate' => false,
        'organization' => false,
        'agent' => false,
        'sum' => false,
        'vat_sum' => false,
        'facture_out' => true,
        'operations' => false,
        'errors' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'meta' => 'meta',
        'id' => 'id',
        'account_id' => 'accountId',
        'applicable' => 'applicable',
        'name' => 'name',
        'code' => 'code',
        'external_code' => 'externalCode',
        'sync_id' => 'syncId',
        'description' => 'description',
        'created' => 'created',
        'deleted' => 'deleted',
        'updated' => 'updated',
        'moment' => 'moment',
        'attributes' => 'attributes',
        'contract' => 'contract',
        'files' => 'files',
        'payment_purpose' => 'paymentPurpose',
        'printed' => 'printed',
        'project' => 'project',
        'published' => 'published',
        'owner' => 'owner',
        'group' => 'group',
        'sales_channel' => 'salesChannel',
        'shared' => 'shared',
        'state' => 'state',
        'rate' => 'rate',
        'organization' => 'organization',
        'agent' => 'agent',
        'sum' => 'sum',
        'vat_sum' => 'vatSum',
        'facture_out' => 'factureOut',
        'operations' => 'operations',
        'errors' => 'errors'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'meta' => 'setMeta',
        'id' => 'setId',
        'account_id' => 'setAccountId',
        'applicable' => 'setApplicable',
        'name' => 'setName',
        'code' => 'setCode',
        'external_code' => 'setExternalCode',
        'sync_id' => 'setSyncId',
        'description' => 'setDescription',
        'created' => 'setCreated',
        'deleted' => 'setDeleted',
        'updated' => 'setUpdated',
        'moment' => 'setMoment',
        'attributes' => 'setAttributes',
        'contract' => 'setContract',
        'files' => 'setFiles',
        'payment_purpose' => 'setPaymentPurpose',
        'printed' => 'setPrinted',
        'project' => 'setProject',
        'published' => 'setPublished',
        'owner' => 'setOwner',
        'group' => 'setGroup',
        'sales_channel' => 'setSalesChannel',
        'shared' => 'setShared',
        'state' => 'setState',
        'rate' => 'setRate',
        'organization' => 'setOrganization',
        'agent' => 'setAgent',
        'sum' => 'setSum',
        'vat_sum' => 'setVatSum',
        'facture_out' => 'setFactureOut',
        'operations' => 'setOperations',
        'errors' => 'setErrors'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'meta' => 'getMeta',
        'id' => 'getId',
        'account_id' => 'getAccountId',
        'applicable' => 'getApplicable',
        'name' => 'getName',
        'code' => 'getCode',
        'external_code' => 'getExternalCode',
        'sync_id' => 'getSyncId',
        'description' => 'getDescription',
        'created' => 'getCreated',
        'deleted' => 'getDeleted',
        'updated' => 'getUpdated',
        'moment' => 'getMoment',
        'attributes' => 'getAttributes',
        'contract' => 'getContract',
        'files' => 'getFiles',
        'payment_purpose' => 'getPaymentPurpose',
        'printed' => 'getPrinted',
        'project' => 'getProject',
        'published' => 'getPublished',
        'owner' => 'getOwner',
        'group' => 'getGroup',
        'sales_channel' => 'getSalesChannel',
        'shared' => 'getShared',
        'state' => 'getState',
        'rate' => 'getRate',
        'organization' => 'getOrganization',
        'agent' => 'getAgent',
        'sum' => 'getSum',
        'vat_sum' => 'getVatSum',
        'facture_out' => 'getFactureOut',
        'operations' => 'getOperations',
        'errors' => 'getErrors'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('meta', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('account_id', $data ?? [], null);
        $this->setIfExists('applicable', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('external_code', $data ?? [], null);
        $this->setIfExists('sync_id', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('created', $data ?? [], null);
        $this->setIfExists('deleted', $data ?? [], null);
        $this->setIfExists('updated', $data ?? [], null);
        $this->setIfExists('moment', $data ?? [], null);
        $this->setIfExists('attributes', $data ?? [], null);
        $this->setIfExists('contract', $data ?? [], null);
        $this->setIfExists('files', $data ?? [], null);
        $this->setIfExists('payment_purpose', $data ?? [], null);
        $this->setIfExists('printed', $data ?? [], null);
        $this->setIfExists('project', $data ?? [], null);
        $this->setIfExists('published', $data ?? [], null);
        $this->setIfExists('owner', $data ?? [], null);
        $this->setIfExists('group', $data ?? [], null);
        $this->setIfExists('sales_channel', $data ?? [], null);
        $this->setIfExists('shared', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('rate', $data ?? [], null);
        $this->setIfExists('organization', $data ?? [], null);
        $this->setIfExists('agent', $data ?? [], null);
        $this->setIfExists('sum', $data ?? [], null);
        $this->setIfExists('vat_sum', $data ?? [], null);
        $this->setIfExists('facture_out', $data ?? [], null);
        $this->setIfExists('operations', $data ?? [], null);
        $this->setIfExists('errors', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['name']) && (mb_strlen($this->container['name']) > 255)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['code']) && (mb_strlen($this->container['code']) > 255)) {
            $invalidProperties[] = "invalid value for 'code', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['external_code']) && (mb_strlen($this->container['external_code']) > 255)) {
            $invalidProperties[] = "invalid value for 'external_code', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 4096)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 4096.";
        }

        if (!is_null($this->container['payment_purpose']) && (mb_strlen($this->container['payment_purpose']) > 255)) {
            $invalidProperties[] = "invalid value for 'payment_purpose', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['errors'] === null) {
            $invalidProperties[] = "'errors' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets meta
     *
     * @return \OpenAPI\Client\Model\Meta|null
     */
    public function getMeta()
    {
        return $this->container['meta'];
    }

    /**
     * Sets meta
     *
     * @param \OpenAPI\Client\Model\Meta|null $meta meta
     *
     * @return self
     */
    public function setMeta($meta)
    {
        if (is_null($meta)) {
            throw new \InvalidArgumentException('non-nullable meta cannot be null');
        }
        $this->container['meta'] = $meta;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id ID Приходного ордера
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets account_id
     *
     * @return string|null
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param string|null $account_id ID учетной записи
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        if (is_null($account_id)) {
            throw new \InvalidArgumentException('non-nullable account_id cannot be null');
        }
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets applicable
     *
     * @return bool|null
     */
    public function getApplicable()
    {
        return $this->container['applicable'];
    }

    /**
     * Sets applicable
     *
     * @param bool|null $applicable Отметка о проведении
     *
     * @return self
     */
    public function setApplicable($applicable)
    {
        if (is_null($applicable)) {
            throw new \InvalidArgumentException('non-nullable applicable cannot be null');
        }
        $this->container['applicable'] = $applicable;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Наименование Приходного ордера
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $name when calling CreateCashInBatch200ResponseInner., must be smaller than or equal to 255.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code Код Приходного ордера
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        if ((mb_strlen($code) > 255)) {
            throw new \InvalidArgumentException('invalid length for $code when calling CreateCashInBatch200ResponseInner., must be smaller than or equal to 255.');
        }

        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets external_code
     *
     * @return string|null
     */
    public function getExternalCode()
    {
        return $this->container['external_code'];
    }

    /**
     * Sets external_code
     *
     * @param string|null $external_code Внешний код Приходного ордера
     *
     * @return self
     */
    public function setExternalCode($external_code)
    {
        if (is_null($external_code)) {
            throw new \InvalidArgumentException('non-nullable external_code cannot be null');
        }
        if ((mb_strlen($external_code) > 255)) {
            throw new \InvalidArgumentException('invalid length for $external_code when calling CreateCashInBatch200ResponseInner., must be smaller than or equal to 255.');
        }

        $this->container['external_code'] = $external_code;

        return $this;
    }

    /**
     * Gets sync_id
     *
     * @return string|null
     */
    public function getSyncId()
    {
        return $this->container['sync_id'];
    }

    /**
     * Sets sync_id
     *
     * @param string|null $sync_id ID синхронизации
     *
     * @return self
     */
    public function setSyncId($sync_id)
    {
        if (is_null($sync_id)) {
            throw new \InvalidArgumentException('non-nullable sync_id cannot be null');
        }
        $this->container['sync_id'] = $sync_id;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Комментарий Приходного ордера
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($description) && (mb_strlen($description) > 4096)) {
            throw new \InvalidArgumentException('invalid length for $description when calling CreateCashInBatch200ResponseInner., must be smaller than or equal to 4096.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets created
     *
     * @return string|null
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param string|null $created Дата создания
     *
     * @return self
     */
    public function setCreated($created)
    {
        if (is_null($created)) {
            throw new \InvalidArgumentException('non-nullable created cannot be null');
        }
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets deleted
     *
     * @return string|null
     */
    public function getDeleted()
    {
        return $this->container['deleted'];
    }

    /**
     * Sets deleted
     *
     * @param string|null $deleted Момент последнего удаления Приходного ордера
     *
     * @return self
     */
    public function setDeleted($deleted)
    {
        if (is_null($deleted)) {
            throw new \InvalidArgumentException('non-nullable deleted cannot be null');
        }
        $this->container['deleted'] = $deleted;

        return $this;
    }

    /**
     * Gets updated
     *
     * @return string|null
     */
    public function getUpdated()
    {
        return $this->container['updated'];
    }

    /**
     * Sets updated
     *
     * @param string|null $updated Момент последнего обновления Приходного ордера
     *
     * @return self
     */
    public function setUpdated($updated)
    {
        if (is_null($updated)) {
            throw new \InvalidArgumentException('non-nullable updated cannot be null');
        }
        $this->container['updated'] = $updated;

        return $this;
    }

    /**
     * Gets moment
     *
     * @return string|null
     */
    public function getMoment()
    {
        return $this->container['moment'];
    }

    /**
     * Sets moment
     *
     * @param string|null $moment Дата документа
     *
     * @return self
     */
    public function setMoment($moment)
    {
        if (is_null($moment)) {
            throw new \InvalidArgumentException('non-nullable moment cannot be null');
        }
        $this->container['moment'] = $moment;

        return $this;
    }

    /**
     * Gets attributes
     *
     * @return \OpenAPI\Client\Model\AttributeAbstract[]|null
     */
    public function getAttributes()
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes
     *
     * @param \OpenAPI\Client\Model\AttributeAbstract[]|null $attributes Коллекция метаданных доп. полей
     *
     * @return self
     */
    public function setAttributes($attributes)
    {
        if (is_null($attributes)) {
            throw new \InvalidArgumentException('non-nullable attributes cannot be null');
        }
        $this->container['attributes'] = $attributes;

        return $this;
    }

    /**
     * Gets contract
     *
     * @return \OpenAPI\Client\Model\Contract|null
     */
    public function getContract()
    {
        return $this->container['contract'];
    }

    /**
     * Sets contract
     *
     * @param \OpenAPI\Client\Model\Contract|null $contract Метаданные договора
     *
     * @return self
     */
    public function setContract($contract)
    {
        if (is_null($contract)) {
            array_push($this->openAPINullablesSetToNull, 'contract');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('contract', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['contract'] = $contract;

        return $this;
    }

    /**
     * Gets files
     *
     * @return \OpenAPI\Client\Model\FileList|null
     */
    public function getFiles()
    {
        return $this->container['files'];
    }

    /**
     * Sets files
     *
     * @param \OpenAPI\Client\Model\FileList|null $files Метаданные массива файлов
     *
     * @return self
     */
    public function setFiles($files)
    {
        if (is_null($files)) {
            array_push($this->openAPINullablesSetToNull, 'files');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('files', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['files'] = $files;

        return $this;
    }

    /**
     * Gets payment_purpose
     *
     * @return string|null
     */
    public function getPaymentPurpose()
    {
        return $this->container['payment_purpose'];
    }

    /**
     * Sets payment_purpose
     *
     * @param string|null $payment_purpose Основание
     *
     * @return self
     */
    public function setPaymentPurpose($payment_purpose)
    {
        if (is_null($payment_purpose)) {
            throw new \InvalidArgumentException('non-nullable payment_purpose cannot be null');
        }
        if ((mb_strlen($payment_purpose) > 255)) {
            throw new \InvalidArgumentException('invalid length for $payment_purpose when calling CreateCashInBatch200ResponseInner., must be smaller than or equal to 255.');
        }

        $this->container['payment_purpose'] = $payment_purpose;

        return $this;
    }

    /**
     * Gets printed
     *
     * @return bool|null
     */
    public function getPrinted()
    {
        return $this->container['printed'];
    }

    /**
     * Sets printed
     *
     * @param bool|null $printed Напечатан ли документ
     *
     * @return self
     */
    public function setPrinted($printed)
    {
        if (is_null($printed)) {
            throw new \InvalidArgumentException('non-nullable printed cannot be null');
        }
        $this->container['printed'] = $printed;

        return $this;
    }

    /**
     * Gets project
     *
     * @return \OpenAPI\Client\Model\Project|null
     */
    public function getProject()
    {
        return $this->container['project'];
    }

    /**
     * Sets project
     *
     * @param \OpenAPI\Client\Model\Project|null $project Метаданные проекта
     *
     * @return self
     */
    public function setProject($project)
    {
        if (is_null($project)) {
            array_push($this->openAPINullablesSetToNull, 'project');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('project', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['project'] = $project;

        return $this;
    }

    /**
     * Gets published
     *
     * @return bool|null
     */
    public function getPublished()
    {
        return $this->container['published'];
    }

    /**
     * Sets published
     *
     * @param bool|null $published Опубликован ли документ
     *
     * @return self
     */
    public function setPublished($published)
    {
        if (is_null($published)) {
            throw new \InvalidArgumentException('non-nullable published cannot be null');
        }
        $this->container['published'] = $published;

        return $this;
    }

    /**
     * Gets owner
     *
     * @return \OpenAPI\Client\Model\Employee|null
     */
    public function getOwner()
    {
        return $this->container['owner'];
    }

    /**
     * Sets owner
     *
     * @param \OpenAPI\Client\Model\Employee|null $owner Владелец (Сотрудник)
     *
     * @return self
     */
    public function setOwner($owner)
    {
        if (is_null($owner)) {
            array_push($this->openAPINullablesSetToNull, 'owner');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('owner', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['owner'] = $owner;

        return $this;
    }

    /**
     * Gets group
     *
     * @return \OpenAPI\Client\Model\Group|null
     */
    public function getGroup()
    {
        return $this->container['group'];
    }

    /**
     * Sets group
     *
     * @param \OpenAPI\Client\Model\Group|null $group group
     *
     * @return self
     */
    public function setGroup($group)
    {
        if (is_null($group)) {
            throw new \InvalidArgumentException('non-nullable group cannot be null');
        }
        $this->container['group'] = $group;

        return $this;
    }

    /**
     * Gets sales_channel
     *
     * @return \OpenAPI\Client\Model\SalesChannel|null
     */
    public function getSalesChannel()
    {
        return $this->container['sales_channel'];
    }

    /**
     * Sets sales_channel
     *
     * @param \OpenAPI\Client\Model\SalesChannel|null $sales_channel Метаданные канала продаж
     *
     * @return self
     */
    public function setSalesChannel($sales_channel)
    {
        if (is_null($sales_channel)) {
            array_push($this->openAPINullablesSetToNull, 'sales_channel');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sales_channel', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sales_channel'] = $sales_channel;

        return $this;
    }

    /**
     * Gets shared
     *
     * @return bool|null
     */
    public function getShared()
    {
        return $this->container['shared'];
    }

    /**
     * Sets shared
     *
     * @param bool|null $shared Общий доступ
     *
     * @return self
     */
    public function setShared($shared)
    {
        if (is_null($shared)) {
            throw new \InvalidArgumentException('non-nullable shared cannot be null');
        }
        $this->container['shared'] = $shared;

        return $this;
    }

    /**
     * Gets state
     *
     * @return \OpenAPI\Client\Model\State|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param \OpenAPI\Client\Model\State|null $state Метаданные статуса Приходного ордера
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            array_push($this->openAPINullablesSetToNull, 'state');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('state', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets rate
     *
     * @return \OpenAPI\Client\Model\CurrencyRate|null
     */
    public function getRate()
    {
        return $this->container['rate'];
    }

    /**
     * Sets rate
     *
     * @param \OpenAPI\Client\Model\CurrencyRate|null $rate rate
     *
     * @return self
     */
    public function setRate($rate)
    {
        if (is_null($rate)) {
            throw new \InvalidArgumentException('non-nullable rate cannot be null');
        }
        $this->container['rate'] = $rate;

        return $this;
    }

    /**
     * Gets organization
     *
     * @return \OpenAPI\Client\Model\Organization|null
     */
    public function getOrganization()
    {
        return $this->container['organization'];
    }

    /**
     * Sets organization
     *
     * @param \OpenAPI\Client\Model\Organization|null $organization organization
     *
     * @return self
     */
    public function setOrganization($organization)
    {
        if (is_null($organization)) {
            throw new \InvalidArgumentException('non-nullable organization cannot be null');
        }
        $this->container['organization'] = $organization;

        return $this;
    }

    /**
     * Gets agent
     *
     * @return \OpenAPI\Client\Model\Counterparty|null
     */
    public function getAgent()
    {
        return $this->container['agent'];
    }

    /**
     * Sets agent
     *
     * @param \OpenAPI\Client\Model\Counterparty|null $agent agent
     *
     * @return self
     */
    public function setAgent($agent)
    {
        if (is_null($agent)) {
            throw new \InvalidArgumentException('non-nullable agent cannot be null');
        }
        $this->container['agent'] = $agent;

        return $this;
    }

    /**
     * Gets sum
     *
     * @return float|null
     */
    public function getSum()
    {
        return $this->container['sum'];
    }

    /**
     * Sets sum
     *
     * @param float|null $sum Сумма Приходного ордера в установленной валюте
     *
     * @return self
     */
    public function setSum($sum)
    {
        if (is_null($sum)) {
            throw new \InvalidArgumentException('non-nullable sum cannot be null');
        }
        $this->container['sum'] = $sum;

        return $this;
    }

    /**
     * Gets vat_sum
     *
     * @return float|null
     */
    public function getVatSum()
    {
        return $this->container['vat_sum'];
    }

    /**
     * Sets vat_sum
     *
     * @param float|null $vat_sum Сумма НДС
     *
     * @return self
     */
    public function setVatSum($vat_sum)
    {
        if (is_null($vat_sum)) {
            throw new \InvalidArgumentException('non-nullable vat_sum cannot be null');
        }
        $this->container['vat_sum'] = $vat_sum;

        return $this;
    }

    /**
     * Gets facture_out
     *
     * @return \OpenAPI\Client\Model\FactureOut|null
     */
    public function getFactureOut()
    {
        return $this->container['facture_out'];
    }

    /**
     * Sets facture_out
     *
     * @param \OpenAPI\Client\Model\FactureOut|null $facture_out Счет-фактура выданный, с которым связан этот платеж
     *
     * @return self
     */
    public function setFactureOut($facture_out)
    {
        if (is_null($facture_out)) {
            array_push($this->openAPINullablesSetToNull, 'facture_out');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('facture_out', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['facture_out'] = $facture_out;

        return $this;
    }

    /**
     * Gets operations
     *
     * @return \OpenAPI\Client\Model\CashInOperation[]|null
     */
    public function getOperations()
    {
        return $this->container['operations'];
    }

    /**
     * Sets operations
     *
     * @param \OpenAPI\Client\Model\CashInOperation[]|null $operations Связанные операции. Допустимые типы по `meta.type`: customerorder, purchasereturn, demand, invoiceout, commissionreportin, retailshift.
     *
     * @return self
     */
    public function setOperations($operations)
    {
        if (is_null($operations)) {
            throw new \InvalidArgumentException('non-nullable operations cannot be null');
        }
        $this->container['operations'] = $operations;

        return $this;
    }

    /**
     * Gets errors
     *
     * @return \OpenAPI\Client\Model\ErrorErrorsInner[]
     */
    public function getErrors()
    {
        return $this->container['errors'];
    }

    /**
     * Sets errors
     *
     * @param \OpenAPI\Client\Model\ErrorErrorsInner[] $errors errors
     *
     * @return self
     */
    public function setErrors($errors)
    {
        if (is_null($errors)) {
            throw new \InvalidArgumentException('non-nullable errors cannot be null');
        }
        $this->container['errors'] = $errors;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


