<?php
/**
 * InternalOrder
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * МойСклад JSON API
 *
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * InternalOrder Class Doc Comment
 *
 * @category Class
 * @description Внутренний заказ
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InternalOrder implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InternalOrder';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'meta' => '\OpenAPI\Client\Model\Meta',
        'id' => 'string',
        'account_id' => 'string',
        'name' => 'string',
        'code' => 'string',
        'external_code' => 'string',
        'sync_id' => 'string',
        'description' => 'string',
        'created' => 'string',
        'deleted' => 'string',
        'updated' => 'string',
        'moment' => 'string',
        'delivery_planned_moment' => 'string',
        'applicable' => 'bool',
        'printed' => 'bool',
        'published' => 'bool',
        'shared' => 'bool',
        'vat_enabled' => 'bool',
        'vat_included' => 'bool',
        'vat_sum' => 'float',
        'sum' => 'float',
        'organization' => '\OpenAPI\Client\Model\Organization',
        'store' => '\OpenAPI\Client\Model\Store',
        'state' => '\OpenAPI\Client\Model\State',
        'project' => '\OpenAPI\Client\Model\Project',
        'owner' => '\OpenAPI\Client\Model\Employee',
        'group' => '\OpenAPI\Client\Model\Group',
        'attributes' => '\OpenAPI\Client\Model\AttributeAbstract[]',
        'files' => '\OpenAPI\Client\Model\FileList',
        'rate' => '\OpenAPI\Client\Model\CurrencyRate',
        'positions' => '\OpenAPI\Client\Model\InternalOrderPositionList',
        'purchase_orders' => '\OpenAPI\Client\Model\PurchaseOrder[]',
        'production_tasks' => '\OpenAPI\Client\Model\ProductionTask[]',
        'moves' => '\OpenAPI\Client\Model\Move[]',
        'processing_order' => '\OpenAPI\Client\Model\ProcessingOrder'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'meta' => null,
        'id' => 'uuid',
        'account_id' => 'uuid',
        'name' => null,
        'code' => null,
        'external_code' => null,
        'sync_id' => 'uuid',
        'description' => null,
        'created' => null,
        'deleted' => null,
        'updated' => null,
        'moment' => null,
        'delivery_planned_moment' => null,
        'applicable' => null,
        'printed' => null,
        'published' => null,
        'shared' => null,
        'vat_enabled' => null,
        'vat_included' => null,
        'vat_sum' => 'double',
        'sum' => 'double',
        'organization' => null,
        'store' => null,
        'state' => null,
        'project' => null,
        'owner' => null,
        'group' => null,
        'attributes' => null,
        'files' => null,
        'rate' => null,
        'positions' => null,
        'purchase_orders' => null,
        'production_tasks' => null,
        'moves' => null,
        'processing_order' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'meta' => false,
        'id' => false,
        'account_id' => false,
        'name' => false,
        'code' => false,
        'external_code' => false,
        'sync_id' => false,
        'description' => true,
        'created' => false,
        'deleted' => false,
        'updated' => false,
        'moment' => false,
        'delivery_planned_moment' => false,
        'applicable' => false,
        'printed' => false,
        'published' => false,
        'shared' => false,
        'vat_enabled' => false,
        'vat_included' => false,
        'vat_sum' => false,
        'sum' => false,
        'organization' => false,
        'store' => true,
        'state' => true,
        'project' => true,
        'owner' => true,
        'group' => false,
        'attributes' => false,
        'files' => true,
        'rate' => false,
        'positions' => false,
        'purchase_orders' => false,
        'production_tasks' => false,
        'moves' => false,
        'processing_order' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'meta' => 'meta',
        'id' => 'id',
        'account_id' => 'accountId',
        'name' => 'name',
        'code' => 'code',
        'external_code' => 'externalCode',
        'sync_id' => 'syncId',
        'description' => 'description',
        'created' => 'created',
        'deleted' => 'deleted',
        'updated' => 'updated',
        'moment' => 'moment',
        'delivery_planned_moment' => 'deliveryPlannedMoment',
        'applicable' => 'applicable',
        'printed' => 'printed',
        'published' => 'published',
        'shared' => 'shared',
        'vat_enabled' => 'vatEnabled',
        'vat_included' => 'vatIncluded',
        'vat_sum' => 'vatSum',
        'sum' => 'sum',
        'organization' => 'organization',
        'store' => 'store',
        'state' => 'state',
        'project' => 'project',
        'owner' => 'owner',
        'group' => 'group',
        'attributes' => 'attributes',
        'files' => 'files',
        'rate' => 'rate',
        'positions' => 'positions',
        'purchase_orders' => 'purchaseOrders',
        'production_tasks' => 'productionTasks',
        'moves' => 'moves',
        'processing_order' => 'processingOrder'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'meta' => 'setMeta',
        'id' => 'setId',
        'account_id' => 'setAccountId',
        'name' => 'setName',
        'code' => 'setCode',
        'external_code' => 'setExternalCode',
        'sync_id' => 'setSyncId',
        'description' => 'setDescription',
        'created' => 'setCreated',
        'deleted' => 'setDeleted',
        'updated' => 'setUpdated',
        'moment' => 'setMoment',
        'delivery_planned_moment' => 'setDeliveryPlannedMoment',
        'applicable' => 'setApplicable',
        'printed' => 'setPrinted',
        'published' => 'setPublished',
        'shared' => 'setShared',
        'vat_enabled' => 'setVatEnabled',
        'vat_included' => 'setVatIncluded',
        'vat_sum' => 'setVatSum',
        'sum' => 'setSum',
        'organization' => 'setOrganization',
        'store' => 'setStore',
        'state' => 'setState',
        'project' => 'setProject',
        'owner' => 'setOwner',
        'group' => 'setGroup',
        'attributes' => 'setAttributes',
        'files' => 'setFiles',
        'rate' => 'setRate',
        'positions' => 'setPositions',
        'purchase_orders' => 'setPurchaseOrders',
        'production_tasks' => 'setProductionTasks',
        'moves' => 'setMoves',
        'processing_order' => 'setProcessingOrder'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'meta' => 'getMeta',
        'id' => 'getId',
        'account_id' => 'getAccountId',
        'name' => 'getName',
        'code' => 'getCode',
        'external_code' => 'getExternalCode',
        'sync_id' => 'getSyncId',
        'description' => 'getDescription',
        'created' => 'getCreated',
        'deleted' => 'getDeleted',
        'updated' => 'getUpdated',
        'moment' => 'getMoment',
        'delivery_planned_moment' => 'getDeliveryPlannedMoment',
        'applicable' => 'getApplicable',
        'printed' => 'getPrinted',
        'published' => 'getPublished',
        'shared' => 'getShared',
        'vat_enabled' => 'getVatEnabled',
        'vat_included' => 'getVatIncluded',
        'vat_sum' => 'getVatSum',
        'sum' => 'getSum',
        'organization' => 'getOrganization',
        'store' => 'getStore',
        'state' => 'getState',
        'project' => 'getProject',
        'owner' => 'getOwner',
        'group' => 'getGroup',
        'attributes' => 'getAttributes',
        'files' => 'getFiles',
        'rate' => 'getRate',
        'positions' => 'getPositions',
        'purchase_orders' => 'getPurchaseOrders',
        'production_tasks' => 'getProductionTasks',
        'moves' => 'getMoves',
        'processing_order' => 'getProcessingOrder'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('meta', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('account_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('external_code', $data ?? [], null);
        $this->setIfExists('sync_id', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('created', $data ?? [], null);
        $this->setIfExists('deleted', $data ?? [], null);
        $this->setIfExists('updated', $data ?? [], null);
        $this->setIfExists('moment', $data ?? [], null);
        $this->setIfExists('delivery_planned_moment', $data ?? [], null);
        $this->setIfExists('applicable', $data ?? [], null);
        $this->setIfExists('printed', $data ?? [], null);
        $this->setIfExists('published', $data ?? [], null);
        $this->setIfExists('shared', $data ?? [], null);
        $this->setIfExists('vat_enabled', $data ?? [], null);
        $this->setIfExists('vat_included', $data ?? [], null);
        $this->setIfExists('vat_sum', $data ?? [], null);
        $this->setIfExists('sum', $data ?? [], null);
        $this->setIfExists('organization', $data ?? [], null);
        $this->setIfExists('store', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('project', $data ?? [], null);
        $this->setIfExists('owner', $data ?? [], null);
        $this->setIfExists('group', $data ?? [], null);
        $this->setIfExists('attributes', $data ?? [], null);
        $this->setIfExists('files', $data ?? [], null);
        $this->setIfExists('rate', $data ?? [], null);
        $this->setIfExists('positions', $data ?? [], null);
        $this->setIfExists('purchase_orders', $data ?? [], null);
        $this->setIfExists('production_tasks', $data ?? [], null);
        $this->setIfExists('moves', $data ?? [], null);
        $this->setIfExists('processing_order', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['name']) && (mb_strlen($this->container['name']) > 255)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['code']) && (mb_strlen($this->container['code']) > 255)) {
            $invalidProperties[] = "invalid value for 'code', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['external_code']) && (mb_strlen($this->container['external_code']) > 255)) {
            $invalidProperties[] = "invalid value for 'external_code', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 4096)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 4096.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets meta
     *
     * @return \OpenAPI\Client\Model\Meta|null
     */
    public function getMeta()
    {
        return $this->container['meta'];
    }

    /**
     * Sets meta
     *
     * @param \OpenAPI\Client\Model\Meta|null $meta meta
     *
     * @return self
     */
    public function setMeta($meta)
    {
        if (is_null($meta)) {
            throw new \InvalidArgumentException('non-nullable meta cannot be null');
        }
        $this->container['meta'] = $meta;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id ID Внутреннего заказа
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets account_id
     *
     * @return string|null
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param string|null $account_id ID учетной записи
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        if (is_null($account_id)) {
            throw new \InvalidArgumentException('non-nullable account_id cannot be null');
        }
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Наименование Внутреннего заказа
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $name when calling InternalOrder., must be smaller than or equal to 255.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code Код Внутреннего заказа
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        if ((mb_strlen($code) > 255)) {
            throw new \InvalidArgumentException('invalid length for $code when calling InternalOrder., must be smaller than or equal to 255.');
        }

        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets external_code
     *
     * @return string|null
     */
    public function getExternalCode()
    {
        return $this->container['external_code'];
    }

    /**
     * Sets external_code
     *
     * @param string|null $external_code Внешний код Внутреннего заказа
     *
     * @return self
     */
    public function setExternalCode($external_code)
    {
        if (is_null($external_code)) {
            throw new \InvalidArgumentException('non-nullable external_code cannot be null');
        }
        if ((mb_strlen($external_code) > 255)) {
            throw new \InvalidArgumentException('invalid length for $external_code when calling InternalOrder., must be smaller than or equal to 255.');
        }

        $this->container['external_code'] = $external_code;

        return $this;
    }

    /**
     * Gets sync_id
     *
     * @return string|null
     */
    public function getSyncId()
    {
        return $this->container['sync_id'];
    }

    /**
     * Sets sync_id
     *
     * @param string|null $sync_id ID синхронизации
     *
     * @return self
     */
    public function setSyncId($sync_id)
    {
        if (is_null($sync_id)) {
            throw new \InvalidArgumentException('non-nullable sync_id cannot be null');
        }
        $this->container['sync_id'] = $sync_id;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Комментарий Внутреннего заказа
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($description) && (mb_strlen($description) > 4096)) {
            throw new \InvalidArgumentException('invalid length for $description when calling InternalOrder., must be smaller than or equal to 4096.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets created
     *
     * @return string|null
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param string|null $created Дата создания
     *
     * @return self
     */
    public function setCreated($created)
    {
        if (is_null($created)) {
            throw new \InvalidArgumentException('non-nullable created cannot be null');
        }
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets deleted
     *
     * @return string|null
     */
    public function getDeleted()
    {
        return $this->container['deleted'];
    }

    /**
     * Sets deleted
     *
     * @param string|null $deleted Момент последнего удаления Внутреннего заказа
     *
     * @return self
     */
    public function setDeleted($deleted)
    {
        if (is_null($deleted)) {
            throw new \InvalidArgumentException('non-nullable deleted cannot be null');
        }
        $this->container['deleted'] = $deleted;

        return $this;
    }

    /**
     * Gets updated
     *
     * @return string|null
     */
    public function getUpdated()
    {
        return $this->container['updated'];
    }

    /**
     * Sets updated
     *
     * @param string|null $updated Момент последнего обновления Внутреннего заказа
     *
     * @return self
     */
    public function setUpdated($updated)
    {
        if (is_null($updated)) {
            throw new \InvalidArgumentException('non-nullable updated cannot be null');
        }
        $this->container['updated'] = $updated;

        return $this;
    }

    /**
     * Gets moment
     *
     * @return string|null
     */
    public function getMoment()
    {
        return $this->container['moment'];
    }

    /**
     * Sets moment
     *
     * @param string|null $moment Дата документа
     *
     * @return self
     */
    public function setMoment($moment)
    {
        if (is_null($moment)) {
            throw new \InvalidArgumentException('non-nullable moment cannot be null');
        }
        $this->container['moment'] = $moment;

        return $this;
    }

    /**
     * Gets delivery_planned_moment
     *
     * @return string|null
     */
    public function getDeliveryPlannedMoment()
    {
        return $this->container['delivery_planned_moment'];
    }

    /**
     * Sets delivery_planned_moment
     *
     * @param string|null $delivery_planned_moment Планируемая дата приемки
     *
     * @return self
     */
    public function setDeliveryPlannedMoment($delivery_planned_moment)
    {
        if (is_null($delivery_planned_moment)) {
            throw new \InvalidArgumentException('non-nullable delivery_planned_moment cannot be null');
        }
        $this->container['delivery_planned_moment'] = $delivery_planned_moment;

        return $this;
    }

    /**
     * Gets applicable
     *
     * @return bool|null
     */
    public function getApplicable()
    {
        return $this->container['applicable'];
    }

    /**
     * Sets applicable
     *
     * @param bool|null $applicable Отметка о проведении
     *
     * @return self
     */
    public function setApplicable($applicable)
    {
        if (is_null($applicable)) {
            throw new \InvalidArgumentException('non-nullable applicable cannot be null');
        }
        $this->container['applicable'] = $applicable;

        return $this;
    }

    /**
     * Gets printed
     *
     * @return bool|null
     */
    public function getPrinted()
    {
        return $this->container['printed'];
    }

    /**
     * Sets printed
     *
     * @param bool|null $printed Напечатан ли документ
     *
     * @return self
     */
    public function setPrinted($printed)
    {
        if (is_null($printed)) {
            throw new \InvalidArgumentException('non-nullable printed cannot be null');
        }
        $this->container['printed'] = $printed;

        return $this;
    }

    /**
     * Gets published
     *
     * @return bool|null
     */
    public function getPublished()
    {
        return $this->container['published'];
    }

    /**
     * Sets published
     *
     * @param bool|null $published Опубликован ли документ
     *
     * @return self
     */
    public function setPublished($published)
    {
        if (is_null($published)) {
            throw new \InvalidArgumentException('non-nullable published cannot be null');
        }
        $this->container['published'] = $published;

        return $this;
    }

    /**
     * Gets shared
     *
     * @return bool|null
     */
    public function getShared()
    {
        return $this->container['shared'];
    }

    /**
     * Sets shared
     *
     * @param bool|null $shared Общий доступ
     *
     * @return self
     */
    public function setShared($shared)
    {
        if (is_null($shared)) {
            throw new \InvalidArgumentException('non-nullable shared cannot be null');
        }
        $this->container['shared'] = $shared;

        return $this;
    }

    /**
     * Gets vat_enabled
     *
     * @return bool|null
     */
    public function getVatEnabled()
    {
        return $this->container['vat_enabled'];
    }

    /**
     * Sets vat_enabled
     *
     * @param bool|null $vat_enabled Учитывается ли НДС
     *
     * @return self
     */
    public function setVatEnabled($vat_enabled)
    {
        if (is_null($vat_enabled)) {
            throw new \InvalidArgumentException('non-nullable vat_enabled cannot be null');
        }
        $this->container['vat_enabled'] = $vat_enabled;

        return $this;
    }

    /**
     * Gets vat_included
     *
     * @return bool|null
     */
    public function getVatIncluded()
    {
        return $this->container['vat_included'];
    }

    /**
     * Sets vat_included
     *
     * @param bool|null $vat_included Включен ли НДС в цену
     *
     * @return self
     */
    public function setVatIncluded($vat_included)
    {
        if (is_null($vat_included)) {
            throw new \InvalidArgumentException('non-nullable vat_included cannot be null');
        }
        $this->container['vat_included'] = $vat_included;

        return $this;
    }

    /**
     * Gets vat_sum
     *
     * @return float|null
     */
    public function getVatSum()
    {
        return $this->container['vat_sum'];
    }

    /**
     * Sets vat_sum
     *
     * @param float|null $vat_sum Сумма НДС
     *
     * @return self
     */
    public function setVatSum($vat_sum)
    {
        if (is_null($vat_sum)) {
            throw new \InvalidArgumentException('non-nullable vat_sum cannot be null');
        }
        $this->container['vat_sum'] = $vat_sum;

        return $this;
    }

    /**
     * Gets sum
     *
     * @return float|null
     */
    public function getSum()
    {
        return $this->container['sum'];
    }

    /**
     * Sets sum
     *
     * @param float|null $sum Сумма Внутреннего заказа в копейках
     *
     * @return self
     */
    public function setSum($sum)
    {
        if (is_null($sum)) {
            throw new \InvalidArgumentException('non-nullable sum cannot be null');
        }
        $this->container['sum'] = $sum;

        return $this;
    }

    /**
     * Gets organization
     *
     * @return \OpenAPI\Client\Model\Organization|null
     */
    public function getOrganization()
    {
        return $this->container['organization'];
    }

    /**
     * Sets organization
     *
     * @param \OpenAPI\Client\Model\Organization|null $organization organization
     *
     * @return self
     */
    public function setOrganization($organization)
    {
        if (is_null($organization)) {
            throw new \InvalidArgumentException('non-nullable organization cannot be null');
        }
        $this->container['organization'] = $organization;

        return $this;
    }

    /**
     * Gets store
     *
     * @return \OpenAPI\Client\Model\Store|null
     */
    public function getStore()
    {
        return $this->container['store'];
    }

    /**
     * Sets store
     *
     * @param \OpenAPI\Client\Model\Store|null $store Метаданные склада
     *
     * @return self
     */
    public function setStore($store)
    {
        if (is_null($store)) {
            array_push($this->openAPINullablesSetToNull, 'store');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('store', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['store'] = $store;

        return $this;
    }

    /**
     * Gets state
     *
     * @return \OpenAPI\Client\Model\State|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param \OpenAPI\Client\Model\State|null $state Метаданные статуса Внутреннего заказа
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            array_push($this->openAPINullablesSetToNull, 'state');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('state', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets project
     *
     * @return \OpenAPI\Client\Model\Project|null
     */
    public function getProject()
    {
        return $this->container['project'];
    }

    /**
     * Sets project
     *
     * @param \OpenAPI\Client\Model\Project|null $project Метаданные проекта
     *
     * @return self
     */
    public function setProject($project)
    {
        if (is_null($project)) {
            array_push($this->openAPINullablesSetToNull, 'project');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('project', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['project'] = $project;

        return $this;
    }

    /**
     * Gets owner
     *
     * @return \OpenAPI\Client\Model\Employee|null
     */
    public function getOwner()
    {
        return $this->container['owner'];
    }

    /**
     * Sets owner
     *
     * @param \OpenAPI\Client\Model\Employee|null $owner Владелец (Сотрудник)
     *
     * @return self
     */
    public function setOwner($owner)
    {
        if (is_null($owner)) {
            array_push($this->openAPINullablesSetToNull, 'owner');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('owner', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['owner'] = $owner;

        return $this;
    }

    /**
     * Gets group
     *
     * @return \OpenAPI\Client\Model\Group|null
     */
    public function getGroup()
    {
        return $this->container['group'];
    }

    /**
     * Sets group
     *
     * @param \OpenAPI\Client\Model\Group|null $group group
     *
     * @return self
     */
    public function setGroup($group)
    {
        if (is_null($group)) {
            throw new \InvalidArgumentException('non-nullable group cannot be null');
        }
        $this->container['group'] = $group;

        return $this;
    }

    /**
     * Gets attributes
     *
     * @return \OpenAPI\Client\Model\AttributeAbstract[]|null
     */
    public function getAttributes()
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes
     *
     * @param \OpenAPI\Client\Model\AttributeAbstract[]|null $attributes Коллекция метаданных доп. полей
     *
     * @return self
     */
    public function setAttributes($attributes)
    {
        if (is_null($attributes)) {
            throw new \InvalidArgumentException('non-nullable attributes cannot be null');
        }
        $this->container['attributes'] = $attributes;

        return $this;
    }

    /**
     * Gets files
     *
     * @return \OpenAPI\Client\Model\FileList|null
     */
    public function getFiles()
    {
        return $this->container['files'];
    }

    /**
     * Sets files
     *
     * @param \OpenAPI\Client\Model\FileList|null $files Метаданные массива Файлов
     *
     * @return self
     */
    public function setFiles($files)
    {
        if (is_null($files)) {
            array_push($this->openAPINullablesSetToNull, 'files');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('files', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['files'] = $files;

        return $this;
    }

    /**
     * Gets rate
     *
     * @return \OpenAPI\Client\Model\CurrencyRate|null
     */
    public function getRate()
    {
        return $this->container['rate'];
    }

    /**
     * Sets rate
     *
     * @param \OpenAPI\Client\Model\CurrencyRate|null $rate rate
     *
     * @return self
     */
    public function setRate($rate)
    {
        if (is_null($rate)) {
            throw new \InvalidArgumentException('non-nullable rate cannot be null');
        }
        $this->container['rate'] = $rate;

        return $this;
    }

    /**
     * Gets positions
     *
     * @return \OpenAPI\Client\Model\InternalOrderPositionList|null
     */
    public function getPositions()
    {
        return $this->container['positions'];
    }

    /**
     * Sets positions
     *
     * @param \OpenAPI\Client\Model\InternalOrderPositionList|null $positions Позиций Внутреннего заказа
     *
     * @return self
     */
    public function setPositions($positions)
    {
        if (is_null($positions)) {
            throw new \InvalidArgumentException('non-nullable positions cannot be null');
        }
        $this->container['positions'] = $positions;

        return $this;
    }

    /**
     * Gets purchase_orders
     *
     * @return \OpenAPI\Client\Model\PurchaseOrder[]|null
     */
    public function getPurchaseOrders()
    {
        return $this->container['purchase_orders'];
    }

    /**
     * Sets purchase_orders
     *
     * @param \OpenAPI\Client\Model\PurchaseOrder[]|null $purchase_orders Коллекция метаданных на связанные заказы поставщику
     *
     * @return self
     */
    public function setPurchaseOrders($purchase_orders)
    {
        if (is_null($purchase_orders)) {
            throw new \InvalidArgumentException('non-nullable purchase_orders cannot be null');
        }
        $this->container['purchase_orders'] = $purchase_orders;

        return $this;
    }

    /**
     * Gets production_tasks
     *
     * @return \OpenAPI\Client\Model\ProductionTask[]|null
     */
    public function getProductionTasks()
    {
        return $this->container['production_tasks'];
    }

    /**
     * Sets production_tasks
     *
     * @param \OpenAPI\Client\Model\ProductionTask[]|null $production_tasks Массив ссылок на связанные производственные задания
     *
     * @return self
     */
    public function setProductionTasks($production_tasks)
    {
        if (is_null($production_tasks)) {
            throw new \InvalidArgumentException('non-nullable production_tasks cannot be null');
        }
        $this->container['production_tasks'] = $production_tasks;

        return $this;
    }

    /**
     * Gets moves
     *
     * @return \OpenAPI\Client\Model\Move[]|null
     */
    public function getMoves()
    {
        return $this->container['moves'];
    }

    /**
     * Sets moves
     *
     * @param \OpenAPI\Client\Model\Move[]|null $moves Коллекция метаданных на связанные заказы перемещения
     *
     * @return self
     */
    public function setMoves($moves)
    {
        if (is_null($moves)) {
            throw new \InvalidArgumentException('non-nullable moves cannot be null');
        }
        $this->container['moves'] = $moves;

        return $this;
    }

    /**
     * Gets processing_order
     *
     * @return \OpenAPI\Client\Model\ProcessingOrder|null
     */
    public function getProcessingOrder()
    {
        return $this->container['processing_order'];
    }

    /**
     * Sets processing_order
     *
     * @param \OpenAPI\Client\Model\ProcessingOrder|null $processing_order Метаданные Заказа на производство
     *
     * @return self
     */
    public function setProcessingOrder($processing_order)
    {
        if (is_null($processing_order)) {
            array_push($this->openAPINullablesSetToNull, 'processing_order');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('processing_order', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['processing_order'] = $processing_order;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


