<?php
/**
 * Variant
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * МойСклад JSON API
 *
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Variant Class Doc Comment
 *
 * @category Class
 * @description Модификация
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Variant implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Variant';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'meta' => '\OpenAPI\Client\Model\Meta',
        'id' => 'string',
        'account_id' => 'string',
        'updated' => 'string',
        'name' => 'string',
        'code' => 'string',
        'external_code' => 'string',
        'archived' => 'bool',
        'description' => 'string',
        'discount_prohibited' => 'bool',
        'product' => '\OpenAPI\Client\Model\Product',
        'characteristics' => '\OpenAPI\Client\Model\VariantCharacteristicValue[]',
        'sale_prices' => '\OpenAPI\Client\Model\SalePrice[]',
        'buy_price' => '\OpenAPI\Client\Model\BuyPrice',
        'min_price' => '\OpenAPI\Client\Model\MinPrice',
        'barcodes' => '\OpenAPI\Client\Model\Barcode[]',
        'packs' => '\OpenAPI\Client\Model\VariantPack[]',
        'images' => '\OpenAPI\Client\Model\ImageList',
        'minimum_stock' => '\OpenAPI\Client\Model\MinimumStockAbstract',
        'things' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'meta' => null,
        'id' => 'uuid',
        'account_id' => 'uuid',
        'updated' => null,
        'name' => null,
        'code' => null,
        'external_code' => null,
        'archived' => null,
        'description' => null,
        'discount_prohibited' => null,
        'product' => null,
        'characteristics' => null,
        'sale_prices' => null,
        'buy_price' => null,
        'min_price' => null,
        'barcodes' => null,
        'packs' => null,
        'images' => null,
        'minimum_stock' => null,
        'things' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'meta' => false,
        'id' => false,
        'account_id' => false,
        'updated' => false,
        'name' => false,
        'code' => false,
        'external_code' => false,
        'archived' => false,
        'description' => true,
        'discount_prohibited' => false,
        'product' => false,
        'characteristics' => false,
        'sale_prices' => false,
        'buy_price' => true,
        'min_price' => false,
        'barcodes' => false,
        'packs' => false,
        'images' => true,
        'minimum_stock' => true,
        'things' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'meta' => 'meta',
        'id' => 'id',
        'account_id' => 'accountId',
        'updated' => 'updated',
        'name' => 'name',
        'code' => 'code',
        'external_code' => 'externalCode',
        'archived' => 'archived',
        'description' => 'description',
        'discount_prohibited' => 'discountProhibited',
        'product' => 'product',
        'characteristics' => 'characteristics',
        'sale_prices' => 'salePrices',
        'buy_price' => 'buyPrice',
        'min_price' => 'minPrice',
        'barcodes' => 'barcodes',
        'packs' => 'packs',
        'images' => 'images',
        'minimum_stock' => 'minimumStock',
        'things' => 'things'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'meta' => 'setMeta',
        'id' => 'setId',
        'account_id' => 'setAccountId',
        'updated' => 'setUpdated',
        'name' => 'setName',
        'code' => 'setCode',
        'external_code' => 'setExternalCode',
        'archived' => 'setArchived',
        'description' => 'setDescription',
        'discount_prohibited' => 'setDiscountProhibited',
        'product' => 'setProduct',
        'characteristics' => 'setCharacteristics',
        'sale_prices' => 'setSalePrices',
        'buy_price' => 'setBuyPrice',
        'min_price' => 'setMinPrice',
        'barcodes' => 'setBarcodes',
        'packs' => 'setPacks',
        'images' => 'setImages',
        'minimum_stock' => 'setMinimumStock',
        'things' => 'setThings'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'meta' => 'getMeta',
        'id' => 'getId',
        'account_id' => 'getAccountId',
        'updated' => 'getUpdated',
        'name' => 'getName',
        'code' => 'getCode',
        'external_code' => 'getExternalCode',
        'archived' => 'getArchived',
        'description' => 'getDescription',
        'discount_prohibited' => 'getDiscountProhibited',
        'product' => 'getProduct',
        'characteristics' => 'getCharacteristics',
        'sale_prices' => 'getSalePrices',
        'buy_price' => 'getBuyPrice',
        'min_price' => 'getMinPrice',
        'barcodes' => 'getBarcodes',
        'packs' => 'getPacks',
        'images' => 'getImages',
        'minimum_stock' => 'getMinimumStock',
        'things' => 'getThings'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('meta', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('account_id', $data ?? [], null);
        $this->setIfExists('updated', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('external_code', $data ?? [], null);
        $this->setIfExists('archived', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('discount_prohibited', $data ?? [], null);
        $this->setIfExists('product', $data ?? [], null);
        $this->setIfExists('characteristics', $data ?? [], null);
        $this->setIfExists('sale_prices', $data ?? [], null);
        $this->setIfExists('buy_price', $data ?? [], null);
        $this->setIfExists('min_price', $data ?? [], null);
        $this->setIfExists('barcodes', $data ?? [], null);
        $this->setIfExists('packs', $data ?? [], null);
        $this->setIfExists('images', $data ?? [], null);
        $this->setIfExists('minimum_stock', $data ?? [], null);
        $this->setIfExists('things', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['name']) && (mb_strlen($this->container['name']) > 255)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['code']) && (mb_strlen($this->container['code']) > 255)) {
            $invalidProperties[] = "invalid value for 'code', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['external_code']) && (mb_strlen($this->container['external_code']) > 255)) {
            $invalidProperties[] = "invalid value for 'external_code', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 4096)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 4096.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets meta
     *
     * @return \OpenAPI\Client\Model\Meta|null
     */
    public function getMeta()
    {
        return $this->container['meta'];
    }

    /**
     * Sets meta
     *
     * @param \OpenAPI\Client\Model\Meta|null $meta meta
     *
     * @return self
     */
    public function setMeta($meta)
    {
        if (is_null($meta)) {
            throw new \InvalidArgumentException('non-nullable meta cannot be null');
        }
        $this->container['meta'] = $meta;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id ID Модификации
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets account_id
     *
     * @return string|null
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param string|null $account_id ID учетной записи
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        if (is_null($account_id)) {
            throw new \InvalidArgumentException('non-nullable account_id cannot be null');
        }
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets updated
     *
     * @return string|null
     */
    public function getUpdated()
    {
        return $this->container['updated'];
    }

    /**
     * Sets updated
     *
     * @param string|null $updated Момент последнего обновления сущности
     *
     * @return self
     */
    public function setUpdated($updated)
    {
        if (is_null($updated)) {
            throw new \InvalidArgumentException('non-nullable updated cannot be null');
        }
        $this->container['updated'] = $updated;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Наименование Модификации
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $name when calling Variant., must be smaller than or equal to 255.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code Код Модификации
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        if ((mb_strlen($code) > 255)) {
            throw new \InvalidArgumentException('invalid length for $code when calling Variant., must be smaller than or equal to 255.');
        }

        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets external_code
     *
     * @return string|null
     */
    public function getExternalCode()
    {
        return $this->container['external_code'];
    }

    /**
     * Sets external_code
     *
     * @param string|null $external_code Внешний код Модификации
     *
     * @return self
     */
    public function setExternalCode($external_code)
    {
        if (is_null($external_code)) {
            throw new \InvalidArgumentException('non-nullable external_code cannot be null');
        }
        if ((mb_strlen($external_code) > 255)) {
            throw new \InvalidArgumentException('invalid length for $external_code when calling Variant., must be smaller than or equal to 255.');
        }

        $this->container['external_code'] = $external_code;

        return $this;
    }

    /**
     * Gets archived
     *
     * @return bool|null
     */
    public function getArchived()
    {
        return $this->container['archived'];
    }

    /**
     * Sets archived
     *
     * @param bool|null $archived Добавлена ли Модификация в архив
     *
     * @return self
     */
    public function setArchived($archived)
    {
        if (is_null($archived)) {
            throw new \InvalidArgumentException('non-nullable archived cannot be null');
        }
        $this->container['archived'] = $archived;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Описание Модификации
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($description) && (mb_strlen($description) > 4096)) {
            throw new \InvalidArgumentException('invalid length for $description when calling Variant., must be smaller than or equal to 4096.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets discount_prohibited
     *
     * @return bool|null
     */
    public function getDiscountProhibited()
    {
        return $this->container['discount_prohibited'];
    }

    /**
     * Sets discount_prohibited
     *
     * @param bool|null $discount_prohibited Признак запрета скидок
     *
     * @return self
     */
    public function setDiscountProhibited($discount_prohibited)
    {
        if (is_null($discount_prohibited)) {
            throw new \InvalidArgumentException('non-nullable discount_prohibited cannot be null');
        }
        $this->container['discount_prohibited'] = $discount_prohibited;

        return $this;
    }

    /**
     * Gets product
     *
     * @return \OpenAPI\Client\Model\Product|null
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param \OpenAPI\Client\Model\Product|null $product product
     *
     * @return self
     */
    public function setProduct($product)
    {
        if (is_null($product)) {
            throw new \InvalidArgumentException('non-nullable product cannot be null');
        }
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets characteristics
     *
     * @return \OpenAPI\Client\Model\VariantCharacteristicValue[]|null
     */
    public function getCharacteristics()
    {
        return $this->container['characteristics'];
    }

    /**
     * Sets characteristics
     *
     * @param \OpenAPI\Client\Model\VariantCharacteristicValue[]|null $characteristics Характеристики Модификации
     *
     * @return self
     */
    public function setCharacteristics($characteristics)
    {
        if (is_null($characteristics)) {
            throw new \InvalidArgumentException('non-nullable characteristics cannot be null');
        }
        $this->container['characteristics'] = $characteristics;

        return $this;
    }

    /**
     * Gets sale_prices
     *
     * @return \OpenAPI\Client\Model\SalePrice[]|null
     */
    public function getSalePrices()
    {
        return $this->container['sale_prices'];
    }

    /**
     * Sets sale_prices
     *
     * @param \OpenAPI\Client\Model\SalePrice[]|null $sale_prices Цены продажи
     *
     * @return self
     */
    public function setSalePrices($sale_prices)
    {
        if (is_null($sale_prices)) {
            throw new \InvalidArgumentException('non-nullable sale_prices cannot be null');
        }
        $this->container['sale_prices'] = $sale_prices;

        return $this;
    }

    /**
     * Gets buy_price
     *
     * @return \OpenAPI\Client\Model\BuyPrice|null
     */
    public function getBuyPrice()
    {
        return $this->container['buy_price'];
    }

    /**
     * Sets buy_price
     *
     * @param \OpenAPI\Client\Model\BuyPrice|null $buy_price Закупочная цена
     *
     * @return self
     */
    public function setBuyPrice($buy_price)
    {
        if (is_null($buy_price)) {
            array_push($this->openAPINullablesSetToNull, 'buy_price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('buy_price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['buy_price'] = $buy_price;

        return $this;
    }

    /**
     * Gets min_price
     *
     * @return \OpenAPI\Client\Model\MinPrice|null
     */
    public function getMinPrice()
    {
        return $this->container['min_price'];
    }

    /**
     * Sets min_price
     *
     * @param \OpenAPI\Client\Model\MinPrice|null $min_price min_price
     *
     * @return self
     */
    public function setMinPrice($min_price)
    {
        if (is_null($min_price)) {
            throw new \InvalidArgumentException('non-nullable min_price cannot be null');
        }
        $this->container['min_price'] = $min_price;

        return $this;
    }

    /**
     * Gets barcodes
     *
     * @return \OpenAPI\Client\Model\Barcode[]|null
     */
    public function getBarcodes()
    {
        return $this->container['barcodes'];
    }

    /**
     * Sets barcodes
     *
     * @param \OpenAPI\Client\Model\Barcode[]|null $barcodes Штрихкоды Модификации
     *
     * @return self
     */
    public function setBarcodes($barcodes)
    {
        if (is_null($barcodes)) {
            throw new \InvalidArgumentException('non-nullable barcodes cannot be null');
        }
        $this->container['barcodes'] = $barcodes;

        return $this;
    }

    /**
     * Gets packs
     *
     * @return \OpenAPI\Client\Model\VariantPack[]|null
     */
    public function getPacks()
    {
        return $this->container['packs'];
    }

    /**
     * Sets packs
     *
     * @param \OpenAPI\Client\Model\VariantPack[]|null $packs Упаковки Модификации
     *
     * @return self
     */
    public function setPacks($packs)
    {
        if (is_null($packs)) {
            throw new \InvalidArgumentException('non-nullable packs cannot be null');
        }
        $this->container['packs'] = $packs;

        return $this;
    }

    /**
     * Gets images
     *
     * @return \OpenAPI\Client\Model\ImageList|null
     */
    public function getImages()
    {
        return $this->container['images'];
    }

    /**
     * Sets images
     *
     * @param \OpenAPI\Client\Model\ImageList|null $images Массив метаданных Изображений
     *
     * @return self
     */
    public function setImages($images)
    {
        if (is_null($images)) {
            array_push($this->openAPINullablesSetToNull, 'images');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('images', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['images'] = $images;

        return $this;
    }

    /**
     * Gets minimum_stock
     *
     * @return \OpenAPI\Client\Model\MinimumStockAbstract|null
     */
    public function getMinimumStock()
    {
        return $this->container['minimum_stock'];
    }

    /**
     * Sets minimum_stock
     *
     * @param \OpenAPI\Client\Model\MinimumStockAbstract|null $minimum_stock Неснижаемый остаток
     *
     * @return self
     */
    public function setMinimumStock($minimum_stock)
    {
        if (is_null($minimum_stock)) {
            array_push($this->openAPINullablesSetToNull, 'minimum_stock');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('minimum_stock', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['minimum_stock'] = $minimum_stock;

        return $this;
    }

    /**
     * Gets things
     *
     * @return string[]|null
     */
    public function getThings()
    {
        return $this->container['things'];
    }

    /**
     * Sets things
     *
     * @param string[]|null $things Серийные номера
     *
     * @return self
     */
    public function setThings($things)
    {
        if (is_null($things)) {
            throw new \InvalidArgumentException('non-nullable things cannot be null');
        }
        $this->container['things'] = $things;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


