<?php
/**
 * ApplicationTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * МойСклад JSON API
 *
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use OpenAPI\Client\Model\Application;
use OpenAPI\Client\Model\Meta;
use OpenAPI\Client\Test\Utils\Asserter;
use OpenAPI\Client\Test\Utils\StringUtil;
use PHPUnit\Framework\TestCase;

class ApplicationTest extends TestCase
{
    public function testPropertyMeta()
    {
        $app = new Application();
        $meta = new Meta();
        $app->setMeta($meta);
        Asserter::assertJsonHasFields($app, ['meta' => []]);
    }

    public function testPropertyId()
    {
        $app = new Application();
        $id = StringUtil::randomUuid();
        $app->setId($id);
        Asserter::assertJsonHasFields($app, ['id' => $id]);
    }

    public function testPropertyAccountId()
    {
        $app = new Application();
        $accountId = StringUtil::randomUuid();
        $app->setAccountId($accountId);
        Asserter::assertJsonHasFields($app, ['account_id' => $accountId]);
    }

    public function testPropertyName()
    {
        $app = new Application();
        $name = "TestApplication";
        $app->setName($name);
        Asserter::assertJsonHasFields($app, ['name' => $name]);
    }

    public function testPropertyAppUid()
    {
        $app = new Application();
        $uid = "APP-123456";
        $app->setAppUid($uid);
        Asserter::assertJsonHasFields($app, ['appUid' => $uid]);
    }
}