<?php
/**
 * AttributeDateTimeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * МойСклад JSON API
 *
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use OpenAPI\Client\Model\AttributeDateTime;
use OpenAPI\Client\Test\Utils\Asserter;
use OpenAPI\Client\Test\Utils\StringUtil;
use PHPUnit\Framework\TestCase;

/**
 * AttributeDateTimeTest Class Doc Comment
 *
 * @category    Class
 * @description AttributeDateTime
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AttributeDateTimeTest extends TestCase
{

    public function testPropertyType()
    {
        $attribute = new AttributeDateTime();
        $attribute->setType(AttributeDateTime::TYPE_TIME);
        Asserter::assertJsonHasFields($attribute, ['type' => AttributeDateTime::TYPE_TIME]);
    }

    public function testPropertyValue()
    {
        $attribute = new AttributeDateTime();
        $date = new \DateTime("2025-09-19T12:00:00Z");
        $attribute->setValue($date);
        Asserter::assertJsonHasFields($attribute, ['value' => StringUtil::toRemap12FormatDate($date)]);
    }
}
