<?php
/**
 * MetaTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * МойСклад JSON API
 *
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use OpenAPI\Client\Model\Meta;
use OpenAPI\Client\Test\Utils\Asserter;
use PHPUnit\Framework\TestCase;

/**
 * MetaTest Class Doc Comment
 *
 * @category    Class
 * @description Метаданные объекта
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MetaTest extends TestCase
{

    public function testPropertyHref()
    {
        $meta = new Meta();
        $href = "https://api.moysklad.ru/api/remap/1.2/entity/product/123";
        $meta->setHref($href);
        Asserter::assertJsonHasFields($meta, ['href' => $href]);
    }

    public function testPropertyMetadataHref()
    {
        $meta = new Meta();
        $metadataHref = "https://api.moysklad.ru/api/remap/1.2/entity/product/metadata";
        $meta->setMetadataHref($metadataHref);
        Asserter::assertJsonHasFields($meta, ['metadataHref' => $metadataHref]);
    }

    public function testPropertyType()
    {
        $meta = new Meta();
        $type = "product";
        $meta->setType($type);
        Asserter::assertJsonHasFields($meta, ['type' => $type]);
    }

    public function testPropertyMediaType()
    {
        $meta = new Meta();
        $mediaType = "application/json";
        $meta->setMediaType($mediaType);
        Asserter::assertJsonHasFields($meta, ['mediaType' => $mediaType]);
    }

    public function testPropertyUuidHref()
    {
        $meta = new Meta();
        $uuidHref = "https://app.moysklad.ru/app/#product/edit?id=123";
        $meta->setUuidHref($uuidHref);
        Asserter::assertJsonHasFields($meta, ['uuidHref' => $uuidHref]);
    }

    public function testPropertyDownloadHref()
    {
        $meta = new Meta();
        $downloadHref = "https://api.moysklad.ru/api/remap/1.2/download/123";
        $meta->setDownloadHref($downloadHref);
        Asserter::assertJsonHasFields($meta, ['downloadHref' => $downloadHref]);
    }
}
