<?php
/**
 * CurrenciesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * МойСклад JSON API
 *
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use OpenAPI\Client\Api\CurrenciesApi;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\Model\Currency;
use OpenAPI\Client\Model\CurrencyList;
use OpenAPI\Client\Model\CurrencyMajorUnit;
use OpenAPI\Client\Model\CurrencyMinorUnit;
use OpenAPI\Client\Model\DeleteInfo;
use OpenAPI\Client\Test\Utils\Asserter;
use OpenAPI\Client\Test\Utils\StringUtil;
use PHPUnit\Framework\Assert;
use PHPUnit\Framework\TestCase;

/**
 * CurrenciesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CurrenciesApiTest extends TestCase
{

    private static CurrenciesApi $api;

    public static function setUpBeforeClass(): void
    {
        $config = Configuration::getDefaultConfiguration()
            ->setHost(getenv('API_HOST') . '/api/remap/1.2')
            ->setUsername(getenv('API_LOGIN'))
            ->setPassword(getenv('API_PASSWORD'));

        CurrenciesApiTest::$api = new CurrenciesApi(null, $config);
    }

    /**
     * Проверка успешной обработки ответа сервера на получение валют
     */
    public function testEntityCurrencyGet(): void
    {
        $prefix = StringUtil::randomUuid();
        $currency1 = new Currency();
        $currency1->setName("$prefix Currency 1");
        $currency1->setCode("001");
        $currency1->setIsoCode("CUR" . $prefix . "1");
        $currency1->setRate(1.0);
        $currency1->setMultiplicity(1);
        $currency1->setRateUpdateType(Currency::RATE_UPDATE_TYPE_MANUAL);
        $currency1 = CurrenciesApiTest::$api->entityCurrencyPost($currency1);

        $currency2 = new Currency();
        $currency2->setName("$prefix Currency 2");
        $currency2->setCode("002");
        $currency2->setIsoCode("CUR" . $prefix . "2");
        $currency2->setRate(2.0);
        $currency2->setMultiplicity(1);
        $currency2->setRateUpdateType(Currency::RATE_UPDATE_TYPE_MANUAL);
        $currency2 = CurrenciesApiTest::$api->entityCurrencyPost($currency2);

        $currency3 = new Currency();
        $currency3->setName("$prefix Currency 3");
        $currency3->setCode("003");
        $currency3->setIsoCode("CUR" . $prefix . "3");
        $currency3->setRate(3.0);
        $currency3->setMultiplicity(1);
        $currency3->setRateUpdateType(Currency::RATE_UPDATE_TYPE_MANUAL);
        $currency3 = CurrenciesApiTest::$api->entityCurrencyPost($currency3);

        Assert::assertNotSame($currency1->getId(), $currency2->getId());
        Assert::assertNotSame($currency2->getId(), $currency3->getId());

        $currencyList_12 = CurrenciesApiTest::$api->entityCurrencyGet(2, 0, null, "name~=$prefix", null, 'name');
        Assert::assertInstanceOf(CurrencyList::class, $currencyList_12);
        Asserter::assertMetaCollection($currencyList_12->getMeta(), 'currency', 3, 2, 'currency');
        Asserter::assertJsonHasFields($currencyList_12, ['meta' => []], false, 'context.employee');
        Asserter::assertJsonHasFields($currencyList_12, [
            'rows' => [
                ['id' => $currency1->getId()],
                ['id' => $currency2->getId()]
            ]], false);

        $currencyList_23 = CurrenciesApiTest::$api->entityCurrencyGet(3, 1, null, "name~=$prefix", null, 'name');
        Assert::assertInstanceOf(CurrencyList::class, $currencyList_23);
        Asserter::assertMetaCollection($currencyList_23->getMeta(), 'currency', 3, 3, 'currency');
        Asserter::assertJsonHasFields($currencyList_23, ['meta' => []], false, 'context.employee');
        Asserter::assertJsonHasFields($currencyList_23, [
            'rows' => [
                ['id' => $currency2->getId()],
                ['id' => $currency3->getId()]
            ]], false);
    }

    /**
     * Проверка обработки ответа сервера на получение валют сопровождаемое ошибкой
     */
    public function testEntityCurrencyGetWithError(): void
    {
        try {
            CurrenciesApiTest::$api->entityCurrencyGet(1, 1, null, "name>123");
            Assert::fail();
        } catch (ApiException $e) {
            Assert::assertEquals(412, $e->getCode());
            Assert::assertNotNull($e->getResponseBody());
        }
    }

    /**
     * Проверка успешной обработки ответа сервера на получение валюты по ID
     */
    public function testEntityCurrencyIdGet()
    {
        $currencyReq = new Currency();

        // Основные поля валюты
        $currencyReq->setName("Тестовая валюта " . StringUtil::randomUuid());
        $currencyReq->setFullName("Полное наименование тестовой валюты");
        $currencyReq->setCode("999"); // Цифровой код
        $currencyReq->setIsoCode("TST" . StringUtil::randomUuid());
        $currencyReq->setMultiplicity(1);
        $currencyReq->setRate(75.50);
        $currencyReq->setIndirect(false);
        $currencyReq->setArchived(false);
        $currencyReq->setDefault(false);
        $currencyReq->setSystem(false);

        // Единицы измерения валюты
        $majorUnit = new CurrencyMajorUnit();
        $majorUnit->setGender("masculine");
        $majorUnit->setS1("рубль");
        $majorUnit->setS2("рубля");
        $majorUnit->setS5("рублей");
        $currencyReq->setMajorUnit($majorUnit);

        $minorUnit = new CurrencyMinorUnit();
        $minorUnit->setGender("feminine");
        $minorUnit->setS1("копейка");
        $minorUnit->setS2("копейки");
        $minorUnit->setS5("копеек");
        $currencyReq->setMinorUnit($minorUnit);

        $currencyResp = CurrenciesApiTest::$api->entityCurrencyPost($currencyReq);

        $currencyId = $currencyResp->getId();
        Assert::assertNotNull($currencyId);
        Asserter::assertMeta($currencyResp->getMeta(), $currencyId, 'currency');

        // Проверка полей
        Assert::assertSame($currencyReq->getName(), $currencyResp->getName());
        Assert::assertSame($currencyReq->getFullName(), $currencyResp->getFullName());
        Assert::assertSame($currencyReq->getCode(), $currencyResp->getCode());
        Assert::assertSame($currencyReq->getIsoCode(), $currencyResp->getIsoCode());
        Assert::assertSame($currencyReq->getMultiplicity(), $currencyResp->getMultiplicity());
        Assert::assertSame($currencyReq->getRate(), $currencyResp->getRate());
        Assert::assertSame($currencyReq->getIndirect(), $currencyResp->getIndirect());
        Assert::assertSame($currencyReq->getArchived(), $currencyResp->getArchived());
        Assert::assertSame($currencyReq->getDefault(), $currencyResp->getDefault());
        Assert::assertSame($currencyReq->getSystem(), $currencyResp->getSystem());

        // Проверка единиц измерения
        $majorUnitResp = $currencyResp->getMajorUnit();
        Assert::assertSame($majorUnit->getGender(), $majorUnitResp->getGender());
        Assert::assertSame($majorUnit->getS1(), $majorUnitResp->getS1());
        Assert::assertSame($majorUnit->getS2(), $majorUnitResp->getS2());
        Assert::assertSame($majorUnit->getS5(), $majorUnitResp->getS5());

        $minorUnitResp = $currencyResp->getMinorUnit();
        Assert::assertSame($minorUnit->getGender(), $minorUnitResp->getGender());
        Assert::assertSame($minorUnit->getS1(), $minorUnitResp->getS1());
        Assert::assertSame($minorUnit->getS2(), $minorUnitResp->getS2());
        Assert::assertSame($minorUnit->getS5(), $minorUnitResp->getS5());
    }

    /**
     * Проверка обработки ответа сервера на получение валюты сопровождаемое ошибкой
     */
    public function testEntityCurrencyIdGetWithError()
    {
        try {
            CurrenciesApiTest::$api->entityCurrencyIdGet(StringUtil::randomUuid());
            Assert::fail();
        } catch (ApiException $e) {
            Assert::assertEquals(404, $e->getCode());
            Assert::assertNotNull($e->getResponseBody());
        }
    }

    /**
     * Проверка обработки ответа сервера на создание валюты сопровождаемое ошибкой
     */
    public function testEntityCurrencyPostWithError()
    {
        try {
            $currency1 = new Currency();
            // Не устанавливаем обязательные поля: name, code, isoCode, rate, rateUpdateType
            CurrenciesApiTest::$api->entityCurrencyPost($currency1);
            Assert::fail();
        } catch (ApiException $e) {
            Assert::assertEquals(412, $e->getCode());
            Assert::assertNotNull($e->getResponseBody());
        }
    }

    /**
     * Проверка успешной обработки ответа сервера на обновление валюты
     */
    public function testEntityCurrencyIdPut()
    {
        $createCurrency = new Currency();
        $createCurrency->setName("Currency Old");
        $createCurrency->setCode("001");
        $createCurrency->setIsoCode("OLD" . StringUtil::randomUuid());
        $createCurrency->setRate(1.0);
        $createCurrency->setMultiplicity(1);
        $createCurrency = CurrenciesApiTest::$api->entityCurrencyPost($createCurrency);

        $updateCurrency = new Currency();
        $updateCurrency->setName("Currency New");
        $updateCurrency->setFullName("Новое полное наименование");
        $updateCurrency->setRate(1.5);
        $updateCurrency->setIndirect(true);
        $updateCurrency = CurrenciesApiTest::$api->entityCurrencyIdPut($createCurrency->getId(), $updateCurrency);

        Assert::assertSame($createCurrency->getId(), $updateCurrency->getId());
        Assert::assertSame("Currency New", $updateCurrency->getName());
        Assert::assertSame("Новое полное наименование", $updateCurrency->getFullName());
        Assert::assertSame(1.5, $updateCurrency->getRate());
        Assert::assertTrue($updateCurrency->getIndirect());
    }

    /**
     * Проверка обработки ответа сервера на обновление валюты сопровождаемое ошибкой
     */
    public function testEntityCurrencyIdPutWithError()
    {
        $currency1 = new Currency();
        $currency1->setName("Currency");
        $currency1->setCode("001");
        $currency1->setIsoCode("TST" . StringUtil::randomUuid());
        $currency1->setRate(1.0);
        $currency1->setMultiplicity(1);
        $currency1->setRateUpdateType(Currency::RATE_UPDATE_TYPE_MANUAL);
        $currency1 = CurrenciesApiTest::$api->entityCurrencyPost($currency1);

        try {
            $updateCurrency = new Currency();
            $updateCurrency->setArchived("INVALID_TYPE"); // Неверный тип обновления курса
            CurrenciesApiTest::$api->entityCurrencyIdPut($currency1->getId(), $updateCurrency);
            Assert::fail();
        } catch (ApiException $e) {
            Assert::assertEquals(400, $e->getCode());
            Assert::assertNotNull($e->getResponseBody());
        }
    }

    /**
     * Проверка успешной обработки ответа сервера удаления валюты
     */
    public function testEntityCurrencyIdDelete()
    {
        $currency = new Currency();
        $currency->setName("Currency for Delete");
        $currency->setCode("999");
        $currency->setIsoCode("DEL" . StringUtil::randomUuid());
        $currency->setRate(1.0);
        $currency->setMultiplicity(1);
        $currency->setRateUpdateType(Currency::RATE_UPDATE_TYPE_MANUAL);
        $currency = CurrenciesApiTest::$api->entityCurrencyPost($currency);
        $resp = CurrenciesApiTest::$api->entityCurrencyIdDeleteWithHttpInfo($currency->getId());
        Assert::assertEquals(200, $resp[1]);
    }

    /**
     * Проверка обработки ответа сервера удаления валюты сопровождаемое ошибкой
     */
    public function testEntityCurrencyIdDeleteWithError()
    {
        try {
            CurrenciesApiTest::$api->entityCurrencyIdDelete(StringUtil::randomUuid());
            Assert::fail();
        } catch (ApiException $e) {
            Assert::assertEquals(404, $e->getCode());
            Assert::assertNotNull($e->getResponseBody());
        }
    }

    /**
     * Тест массового создания валют
     */
    public function testBatchCreateCurrencies(): void
    {
        $prefix = StringUtil::randomUuid();
        $currencies = [];

        for ($i = 1; $i <= 3; $i++) {
            $currency = new Currency();
            $currency->setName("$prefix Batch Currency $i");
            $currency->setFullName("Полное наименование валюты $i");
            $currency->setCode((string)(900 + $i));
            $currency->setIsoCode("BCH$i" . $prefix);
            $currency->setRate(10.0 + $i);
            $currency->setIndirect(false);
            $currency->setArchived(false);
            $currency->setDefault(false);
            $currency->setSystem(false);

            $majorUnit = new CurrencyMajorUnit();
            $majorUnit->setGender("masculine");
            $majorUnit->setS1("доллар");
            $majorUnit->setS2("доллара");
            $majorUnit->setS5("долларов");
            $currency->setMajorUnit($majorUnit);

            $minorUnit = new CurrencyMinorUnit();
            $minorUnit->setGender("feminine");
            $minorUnit->setS1("цент");
            $minorUnit->setS2("цента");
            $minorUnit->setS5("центов");
            $currency->setMinorUnit($minorUnit);

            $currencies[] = $currency;
        }

        $response = CurrenciesApiTest::$api->entityCurrencyBatchPost($currencies);

        Assert::assertIsArray($response);
        Assert::assertCount(3, $response);

        foreach ($response as $index => $createdCurrency) {
            Assert::assertInstanceOf(Currency::class, $createdCurrency);
            Assert::assertNotNull($createdCurrency->getId());
            Asserter::assertStringContainsString("$prefix Batch Currency " . ($index + 1), $createdCurrency->getName());
            Assert::assertEquals((string)(900 + $index + 1), $createdCurrency->getCode());
            Asserter::assertStringContainsString("BCH" . ($index + 1) . $prefix, $createdCurrency->getIsoCode());
            Assert::assertEquals(10.0 + ($index + 1), $createdCurrency->getRate());
            Assert::assertFalse($createdCurrency->getIndirect());
            Assert::assertFalse($createdCurrency->getArchived());
            Assert::assertFalse($createdCurrency->getDefault());
            Assert::assertFalse($createdCurrency->getSystem());

            Asserter::assertMeta($createdCurrency->getMeta(), $createdCurrency->getId(), 'currency');
        }
    }

    /**
     * Тест массового обновления валют
     */
    public function testBatchUpdateCurrencies(): void
    {
        $prefix = StringUtil::randomUuid();
        $createdCurrencies = [];

        for ($i = 1; $i <= 3; $i++) {
            $currency = new Currency();
            $currency->setName("$prefix Original Currency $i");
            $currency->setCode((string)(800 + $i));
            $currency->setIsoCode("ORG$i" . $prefix);
            $currency->setRate(5.0 + $i);
            $currency->setMultiplicity(1);
            $currency->setIndirect(false);
            $currency->setArchived(false);
            $createdCurrencies[] = $currency;
        }

        $response = CurrenciesApiTest::$api->entityCurrencyBatchPost($createdCurrencies);
        Assert::assertCount(3, $response);

        $updatedCurrencies = [];
        foreach ($response as $index => $createdCurrency) {
            $updateCurrency = new Currency();
            $updateCurrency->setMeta($createdCurrency->getMeta());
            $updateCurrency->setName("$prefix Updated Currency " . ($index + 1));
            $updateCurrency->setFullName("Обновленное полное наименование " . ($index + 1));
            $updateCurrency->setRate(20.0 + ($index + 1));
            $updateCurrency->setArchived(false);
            $updatedCurrencies[] = $updateCurrency;
        }

        $updateResponse = CurrenciesApiTest::$api->entityCurrencyBatchPost($updatedCurrencies);

        Assert::assertIsArray($updateResponse);
        Assert::assertCount(3, $updateResponse);

        foreach ($updateResponse as $index => $updatedCurrency) {
            Assert::assertInstanceOf(Currency::class, $updatedCurrency);
            Asserter::assertStringContainsString("$prefix Updated Currency " . ($index + 1), $updatedCurrency->getName());
            Asserter::assertStringContainsString("Обновленное полное наименование " . ($index + 1), $updatedCurrency->getFullName());
            Assert::assertEquals(20.0 + ($index + 1), $updatedCurrency->getRate());
        }
    }

    /**
     * Тест массового удаления валют
     */
    public function testBatchDeleteCurrencies(): void
    {
        $prefix = StringUtil::randomUuid();
        $createdCurrencies = [];

        for ($i = 1; $i <= 3; $i++) {
            $currency = new Currency();
            $currency->setName("$prefix Delete Currency $i");
            $currency->setCode((string)(700 + $i));
            $currency->setIsoCode("DEL$i" . $prefix);
            $currency->setRate(1.0);
            $currency->setMultiplicity(1);
            $currency->setRateUpdateType(Currency::RATE_UPDATE_TYPE_MANUAL);
            $createdCurrencies[] = $currency;
        }

        $response = CurrenciesApiTest::$api->entityCurrencyBatchPost($createdCurrencies);
        Assert::assertCount(3, $response);

        $metaArray = [];
        foreach ($response as $createdCurrency) {
            $meta = new Currency();
            $meta->setMeta($createdCurrency->getMeta());
            $metaArray[] = $meta;
        }

        $deleteResponse = CurrenciesApiTest::$api->entityCurrencyDeletePost($metaArray);

        Assert::assertIsArray($deleteResponse);
        Assert::assertCount(3, $deleteResponse);

        foreach ($deleteResponse as $deleteResult) {
            Assert::assertInstanceOf(DeleteInfo::class, $deleteResult);
            Assert::assertNotNull($deleteResult->getInfo());
            Asserter::assertStringContainsString('удален', $deleteResult->getInfo());
        }

        foreach ($response as $createdCurrency) {
            try {
                CurrenciesApiTest::$api->entityCurrencyIdGet($createdCurrency->getId());
                Assert::fail('Валюта должна была быть удалена');
            } catch (ApiException $e) {
                Assert::assertEquals(404, $e->getCode());
            }
        }
    }

    /**
     * Тест массового создания валют с дублирующимися кодами
     */
    public function testBatchCreateCurrenciesWithError(): void
    {
        $prefix = StringUtil::randomUuid();
        $duplicateCode = "777";
        $duplicateIsoCode = "DUP" . $prefix;
        $currencies = [];

        $currency = new Currency();
        $currency->setName("$prefix Duplicate Currency 1");
        $currency->setCode($duplicateCode);
        $currency->setIsoCode("701");
        $currency->setRate(1.0);
        $currency->setMultiplicity(1);
        $currencies[] = $currency;
        for ($i = 2; $i <= 3; $i++) {
            $currency = new Currency();
            $currency->setName("$prefix Duplicate Currency $i");
            $currency->setCode($duplicateCode);
            $currency->setIsoCode((string)(700 + $i));
            $currency->setRate("1.0"); // не правильный тип
            $currency->setMultiplicity(1);
            $currencies[] = $currency;
        }

        try {
            $res = CurrenciesApiTest::$api->entityCurrencyBatchPost($currencies);
        } catch (ApiException $e) {
            $res = json_decode($e->getResponseBody(), true);
        }

        $success = 0;
        $errors = 0;
        foreach ($res as $item) {
            if (isset($item['errors'])) {
                $errors++;
            } else {
                $success++;
                Assert::assertEquals($duplicateCode, $item['code']);
            }
        }

        Assert::assertGreaterThanOrEqual(1, $success, 'Ожидается как минимум 1 успешное создание');
        Assert::assertGreaterThanOrEqual(1, $errors, 'Ожидается как минимум 1 ошибка');
    }

    /**
     * Тест массового удаления валют с некорректными мета-данными
     */
    public function testBatchDeleteCurrenciesWithError(): void
    {
        $prefix = StringUtil::randomUuid();

        $currency = new Currency();
        $currency->setName("$prefix Delete Currency");
        $currency->setCode("888");
        $currency->setIsoCode("DEL" . $prefix);
        $currency->setRate(1.0);
        $currency->setMultiplicity(1);
        $currency->setRateUpdateType(Currency::RATE_UPDATE_TYPE_MANUAL);

        $response = CurrenciesApiTest::$api->entityCurrencyPost($currency);

        $metaArray = [];

        $meta1 = new Currency();
        $meta1->setMeta($response->getMeta());
        $metaArray[] = $meta1;

        // Мета-данные с некорректным ID
        $meta2 = new Currency();
        $metaInvalidId = clone $response->getMeta();
        $newHref = preg_replace(
            '/[0-9a-fA-F-]{36}/',
            'invalid-uuid',
            $metaInvalidId->getHref()
        );
        $metaInvalidId->setHref($newHref);

        $meta2->setMeta($metaInvalidId);
        $metaArray[] = $meta2;

        // Мета-данные с некорректным типом
        $meta3 = new Currency();
        $metaInvalidType = clone $response->getMeta();
        $newHref2 = str_replace('/currency/', '/counterparty/', $metaInvalidType->getHref());
        $newHref2 = preg_replace(
            '/[0-9a-fA-F-]{36}/',
            'invalid-uuid',
            $newHref2
        );
        $metaInvalidType->setHref($newHref2);
        $meta3->setMeta($metaInvalidType);
        $metaArray[] = $meta3;

        try {
            $res = CurrenciesApiTest::$api->entityCurrencyDeletePost($metaArray);
            Assert::fail('Ожидалось исключение ApiException из-за некорректных мета-данных');
        } catch (ApiException $e) {
            $res = json_decode($e->getResponseBody(), true);
        }

        $success = 0;
        $errors = 0;
        foreach ($res as $item) {
            if (isset($item['errors'])) {
                $errors++;
            } else {
                $success++;
                Asserter::assertStringContainsString('удален', $item['info']);
            }
        }

        Assert::assertSame(1, $success, 'Ожидается 1 успешное удаление');
        Assert::assertSame(2, $errors, 'Ожидается 2 ошибки');
    }

    /**
     * Тест массового удаления валют с пустым массивом
     */
    public function testBatchDeleteCurrenciesWithEmptyArray(): void
    {
        try {
            CurrenciesApiTest::$api->entityCurrencyDeletePost([]);
            Assert::fail('Ожидалось исключение InvalidArgumentException для пустого массива');
        } catch (\InvalidArgumentException $e) {
            Asserter::assertStringContainsString('Missing the required parameter', $e->getMessage());
        }
    }
}