<?php
/**
 * EmployeesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * МойСклад JSON API
 *
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use OpenAPI\Client\Api\EmployeesApi;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\Model\Cashier;
use OpenAPI\Client\Model\DeleteInfo;
use OpenAPI\Client\Model\Employee;
use OpenAPI\Client\Model\EmployeeList;
use OpenAPI\Client\Model\EmployeeSalary;
use OpenAPI\Client\Model\Image;
use OpenAPI\Client\Test\Utils\Asserter;
use OpenAPI\Client\Test\Utils\StringUtil;
use PHPUnit\Framework\Assert;
use PHPUnit\Framework\TestCase;

/**
 * EmployeesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmployeesApiTest extends TestCase
{

    private static EmployeesApi $api;

    public static function setUpBeforeClass(): void
    {
        $config = Configuration::getDefaultConfiguration()
            ->setHost(getenv('API_HOST') . '/api/remap/1.2')
            ->setUsername(getenv('API_LOGIN'))
            ->setPassword(getenv('API_PASSWORD'));

        EmployeesApiTest::$api = new EmployeesApi(null, $config);
    }

    /**
     * Проверка успешной обработки ответа сервера на получение сотрудников
     */
    public function testEntityEmployeeGet(): void
    {
        $prefix = StringUtil::randomUuid();
        $employee1 = new Employee();
        $employee1->setFirstName("Иван");
        $employee1->setLastName("$prefix Employee 1");
        $employee1->setPosition("Менеджер");
        $employee1->setPhone("+79991234567");
        $employee1 = EmployeesApiTest::$api->entityEmployeePost($employee1);

        $employee2 = new Employee();
        $employee2->setFirstName("Петр");
        $employee2->setLastName("$prefix Employee 2");
        $employee2->setPosition("Продавец");
        $employee2->setPhone("+79991234568");
        $employee2 = EmployeesApiTest::$api->entityEmployeePost($employee2);

        $employee3 = new Employee();
        $employee3->setFirstName("Сергей");
        $employee3->setLastName("$prefix Employee 3");
        $employee3->setPosition("Директор");
        $employee3->setPhone("+79991234569");
        $employee3 = EmployeesApiTest::$api->entityEmployeePost($employee3);

        Assert::assertNotSame($employee1->getId(), $employee2->getId());
        Assert::assertNotSame($employee2->getId(), $employee3->getId());

        $employeeList_12 = EmployeesApiTest::$api->entityEmployeeGet(2, 0, null, "lastName~=$prefix", null, 'lastName');
        Assert::assertInstanceOf(EmployeeList::class, $employeeList_12);
        Asserter::assertMetaCollection($employeeList_12->getMeta(), 'employee', 3, 2, 'employee');
        Asserter::assertJsonHasFields($employeeList_12, ['meta' => []], false, 'context.employee');
        Asserter::assertJsonHasFields($employeeList_12, [
            'rows' => [
                ['id' => $employee1->getId()],
                ['id' => $employee2->getId()]
            ]], false);

        $employeeList_23 = EmployeesApiTest::$api->entityEmployeeGet(3, 1, null, "lastName~=$prefix", null, 'lastName');
        Assert::assertInstanceOf(EmployeeList::class, $employeeList_23);
        Asserter::assertMetaCollection($employeeList_23->getMeta(), 'employee', 3, 3, 'employee');
        Asserter::assertJsonHasFields($employeeList_23, ['meta' => []], false, 'context.employee');
        Asserter::assertJsonHasFields($employeeList_23, [
            'rows' => [
                ['id' => $employee2->getId()],
                ['id' => $employee3->getId()]
            ]], false);
    }

    /**
     * Проверка обработки ответа сервера на получение сотрудников сопровождаемое ошибкой
     */
    public function testEntityEmployeeGetWithError(): void
    {
        try {
            EmployeesApiTest::$api->entityEmployeeGet(1, 1, null, "lastName>123");
            Assert::fail();
        } catch (ApiException $e) {
            Assert::assertEquals(412, $e->getCode());
            Assert::assertNotNull($e->getResponseBody());
        }
    }

    /**
     * Проверка успешной обработки ответа сервера на получение сотрудника по ID
     */
    public function testEntityEmployeeIdGet()
    {
        $employeeReq = new Employee();

        // Основные поля сотрудника
        $employeeReq->setFirstName("Иван");
        $employeeReq->setMiddleName("Иванович");
        $employeeReq->setLastName("Иванов " . StringUtil::randomUuid());
        $employeeReq->setPosition("Старший менеджер");
        $employeeReq->setPhone("+79991234567");
        $employeeReq->setEmail("ivan.ivanov@" . StringUtil::randomUuid() . ".test");
        $employeeReq->setDescription("Тестовый сотрудник для проверки API");
        $employeeReq->setArchived(false);
        $employeeReq->setShared(true);

        // Зарплата сотрудника
        $salary = new EmployeeSalary();
        $salary->setValue(100000.0);
        $employeeReq->setSalary($salary);

        $employeeResp = EmployeesApiTest::$api->entityEmployeePost($employeeReq);

        $employeeId = $employeeResp->getId();
        Assert::assertNotNull($employeeId);
        Asserter::assertMeta($employeeResp->getMeta(), $employeeId, 'employee');

        // Проверка полей
        Assert::assertSame($employeeReq->getFirstName(), $employeeResp->getFirstName());
        Assert::assertSame($employeeReq->getMiddleName(), $employeeResp->getMiddleName());
        Assert::assertSame($employeeReq->getLastName(), $employeeResp->getLastName());
        Assert::assertSame($employeeReq->getPosition(), $employeeResp->getPosition());
        Assert::assertSame($employeeReq->getPhone(), $employeeResp->getPhone());
        Assert::assertSame($employeeReq->getEmail(), $employeeResp->getEmail());
        Assert::assertSame($employeeReq->getDescription(), $employeeResp->getDescription());
        Assert::assertSame($employeeReq->getInn(), $employeeResp->getInn());
        Assert::assertSame($employeeReq->getArchived(), $employeeResp->getArchived());
        Assert::assertSame($employeeReq->getShared(), $employeeResp->getShared());

        // Проверка имени (полного и короткого)
        Assert::assertNotNull($employeeResp->getName());
        Assert::assertNotNull($employeeResp->getFullName());
        Assert::assertNotNull($employeeResp->getShortFio());

        // Проверка зарплаты
        $salaryResp = $employeeResp->getSalary();
        Assert::assertSame($salary->getValue(), $salaryResp->getValue());

        Asserter::assertJsonHasFields($employeeResp, ['owner' => ['meta' => ['type' => 'employee']]], false);
        Asserter::assertJsonHasFields($employeeResp, ['group' => ['meta' => ['type' => 'group']]], false);
        Assert::assertNotNull($employeeResp->getCreated());
        Assert::assertNotNull($employeeResp->getUpdated());
        Assert::assertNotNull($employeeResp->getAccountId());
    }

    /**
     * Проверка обработки ответа сервера на получение сотрудника сопровождаемое ошибкой
     */
    public function testEntityEmployeeIdGetWithError()
    {
        try {
            EmployeesApiTest::$api->entityEmployeeIdGet(StringUtil::randomUuid());
            Assert::fail();
        } catch (ApiException $e) {
            Assert::assertEquals(404, $e->getCode());
            Assert::assertNotNull($e->getResponseBody());
        }
    }

    /**
     * Проверка обработки ответа сервера на создание сотрудника сопровождаемое ошибкой
     */
    public function testEntityEmployeePostWithError()
    {
        try {
            $employee1 = new Employee();
            // Не устанавливаем обязательные поля (имя, фамилия или position)
            EmployeesApiTest::$api->entityEmployeePost($employee1);
            Assert::fail();
        } catch (ApiException $e) {
            Assert::assertEquals(412, $e->getCode());
            Assert::assertNotNull($e->getResponseBody());
        }
    }

    /**
     * Проверка успешной обработки ответа сервера на обновление сотрудника
     */
    public function testEntityEmployeeIdPut()
    {
        $createEmployee = new Employee();
        $createEmployee->setFirstName("СтароеИмя");
        $createEmployee->setLastName("СтараяФамилия");
        $createEmployee->setPosition("Старая должность");
        $createEmployee = EmployeesApiTest::$api->entityEmployeePost($createEmployee);

        $updateEmployee = new Employee();
        $updateEmployee->setFirstName("НовоеИмя");
        $updateEmployee->setLastName("НоваяФамилия");
        $updateEmployee->setPosition("Новая должность");
        $updateEmployee->setDescription("Обновленное описание сотрудника");
        $updateEmployee = EmployeesApiTest::$api->entityEmployeeIdPut($createEmployee->getId(), $updateEmployee);

        Assert::assertSame($createEmployee->getId(), $updateEmployee->getId());
        Assert::assertSame("НовоеИмя", $updateEmployee->getFirstName());
        Assert::assertSame("НоваяФамилия", $updateEmployee->getLastName());
        Assert::assertSame("Новая должность", $updateEmployee->getPosition());
        Assert::assertSame("Обновленное описание сотрудника", $updateEmployee->getDescription());
    }

    /**
     * Проверка обработки ответа сервера на обновление сотрудника сопровождаемое ошибкой
     */
    public function testEntityEmployeeIdPutWithError()
    {
        $employee1 = new Employee();
        $employee1->setFirstName("Иван");
        $employee1->setLastName("Иванов");
        $employee1->setPosition("Менеджер");
        $employee1 = EmployeesApiTest::$api->entityEmployeePost($employee1);

        try {
            $updateEmployee = new Employee();
            $updateEmployee->setPhone(true); // Неверный формат телефона
            EmployeesApiTest::$api->entityEmployeeIdPut($employee1->getId(), $updateEmployee);
            Assert::fail();
        } catch (ApiException $e) {
            Assert::assertEquals(400, $e->getCode());
            Assert::assertNotNull($e->getResponseBody());
        }
    }

    /**
     * Проверка успешной обработки ответа сервера удаления сотрудника
     */
    public function testEntityEmployeeIdDelete()
    {
        $employee = new Employee();
        $employee->setFirstName("Удаляемый");
        $employee->setLastName("Сотрудник");
        $employee->setPosition("Тестовая должность");
        $employee = EmployeesApiTest::$api->entityEmployeePost($employee);
        $resp = EmployeesApiTest::$api->entityEmployeeIdDeleteWithHttpInfo($employee->getId());
        Assert::assertEquals(200, $resp[1]);
    }

    /**
     * Проверка обработки ответа сервера удаления сотрудника сопровождаемое ошибкой
     */
    public function testEntityEmployeeIdDeleteWithError()
    {
        try {
            EmployeesApiTest::$api->entityEmployeeIdDelete(StringUtil::randomUuid());
            Assert::fail();
        } catch (ApiException $e) {
            Assert::assertEquals(404, $e->getCode());
            Assert::assertNotNull($e->getResponseBody());
        }
    }

    /**
     * Тест массового создания сотрудников
     */
    public function testBatchCreateEmployees(): void
    {
        $prefix = StringUtil::randomUuid();
        $employees = [];

        for ($i = 1; $i <= 3; $i++) {
            $employee = new Employee();
            $employee->setFirstName("Имя$i");
            $employee->setLastName("$prefix Batch Employee $i");
            $employee->setPosition("Должность $i");
            $employee->setPhone("+79991234" . (100 + $i));
            $employee->setEmail("employee$i@" . $prefix . ".test");
            $employee->setDescription("Описание массового сотрудника $i");
            $employee->setArchived(false);
            $employee->setShared(true);

            $salary = new EmployeeSalary();
            $salary->setValue(50000.0 + ($i * 10000));
            $employee->setSalary($salary);

            $employees[] = $employee;
        }

        $response = EmployeesApiTest::$api->entityEmployeeBatchPost($employees);

        Assert::assertIsArray($response);
        Assert::assertCount(3, $response);

        foreach ($response as $index => $createdEmployee) {
            Assert::assertInstanceOf(Employee::class, $createdEmployee);
            Assert::assertNotNull($createdEmployee->getId());
            Asserter::assertStringContainsString("Имя" . ($index + 1), $createdEmployee->getFirstName());
            Asserter::assertStringContainsString("$prefix Batch Employee " . ($index + 1), $createdEmployee->getLastName());
            Asserter::assertStringContainsString("Должность " . ($index + 1), $createdEmployee->getPosition());
            Asserter::assertStringContainsString("Описание массового сотрудника " . ($index + 1), $createdEmployee->getDescription());
            Assert::assertFalse($createdEmployee->getArchived());
            Assert::assertTrue($createdEmployee->getShared());

            $salaryResp = $createdEmployee->getSalary();
            Assert::assertEquals(50000.0 + (($index + 1) * 10000), $salaryResp->getValue());

            Asserter::assertMeta($createdEmployee->getMeta(), $createdEmployee->getId(), 'employee');
        }
    }

    /**
     * Тест массового обновления сотрудников
     */
    public function testBatchUpdateEmployees(): void
    {
        $prefix = StringUtil::randomUuid();
        $createdEmployees = [];

        for ($i = 1; $i <= 3; $i++) {
            $employee = new Employee();
            $employee->setFirstName("Имя$i");
            $employee->setLastName("$prefix Original Employee $i");
            $employee->setPosition("Оригинальная должность $i");
            $employee->setPhone("+79991234" . (200 + $i));
            $employee->setEmail("original$i@" . $prefix . ".test");
            $employee->setArchived(false);
            $createdEmployees[] = $employee;
        }

        $response = EmployeesApiTest::$api->entityEmployeeBatchPost($createdEmployees);
        Assert::assertCount(3, $response);

        $updatedEmployees = [];
        foreach ($response as $index => $createdEmployee) {
            $updateEmployee = new Employee();
            $updateEmployee->setMeta($createdEmployee->getMeta()); // Важно: устанавливаем meta!
            $updateEmployee->setFirstName("ОбновленноеИмя" . ($index + 1));
            $updateEmployee->setLastName("$prefix Updated Employee " . ($index + 1));
            $updateEmployee->setPosition("Обновленная должность " . ($index + 1));
            $updateEmployee->setDescription("Обновленное описание сотрудника " . ($index + 1));
            $updateEmployee->setEmail("updated" . ($index + 1) . "@" . $prefix . ".test");
            $updatedEmployees[] = $updateEmployee;
        }

        try {
            $updateResponse = EmployeesApiTest::$api->entityEmployeeBatchPost($updatedEmployees);
        } catch(ApiException $e) {
            fwrite(STDERR, "Error Message: " . $e->getMessage() . PHP_EOL);
            fwrite(STDERR, "Error Code: " . $e->getCode() . PHP_EOL);
            fwrite(STDERR, "Response Body: " . $e->getResponseBody() . PHP_EOL);
            throw $e;
        }

        Assert::assertIsArray($updateResponse);
        Assert::assertCount(3, $updateResponse);

        foreach ($updateResponse as $index => $updatedEmployee) {
            Assert::assertInstanceOf(Employee::class, $updatedEmployee);
            Asserter::assertStringContainsString("ОбновленноеИмя" . ($index + 1), $updatedEmployee->getFirstName());
            Asserter::assertStringContainsString("$prefix Updated Employee " . ($index + 1), $updatedEmployee->getLastName());
            Asserter::assertStringContainsString("Обновленная должность " . ($index + 1), $updatedEmployee->getPosition());
            Asserter::assertStringContainsString("Обновленное описание сотрудника " . ($index + 1), $updatedEmployee->getDescription());
            Asserter::assertStringContainsString("updated" . ($index + 1) . "@" . $prefix . ".test", $updatedEmployee->getEmail());
        }
    }

    /**
     * Тест массового удаления сотрудников
     */
    public function testBatchDeleteEmployees(): void
    {
        $prefix = StringUtil::randomUuid();
        $createdEmployees = [];

        for ($i = 1; $i <= 3; $i++) {
            $employee = new Employee();
            $employee->setFirstName("Удаляемый$i");
            $employee->setLastName("$prefix Delete Employee $i");
            $employee->setPosition("Должность для удаления $i");
            $employee->setPhone("+79991234" . (300 + $i));
            $createdEmployees[] = $employee;
        }

        $response = EmployeesApiTest::$api->entityEmployeeBatchPost($createdEmployees);
        Assert::assertCount(3, $response);

        $metaArray = [];
        foreach ($response as $createdEmployee) {
            $meta = new Employee();
            $meta->setMeta($createdEmployee->getMeta());
            $metaArray[] = $meta;
        }

        $deleteResponse = EmployeesApiTest::$api->entityEmployeeDeletePost($metaArray);

        Assert::assertIsArray($deleteResponse);
        Assert::assertCount(3, $deleteResponse);

        foreach ($deleteResponse as $deleteResult) {
            Assert::assertInstanceOf(DeleteInfo::class, $deleteResult);
            Assert::assertNotNull($deleteResult->getInfo());
            Asserter::assertStringContainsString('удален', $deleteResult->getInfo());
        }

        foreach ($response as $createdEmployee) {
            try {
                EmployeesApiTest::$api->entityEmployeeIdGet($createdEmployee->getId());
                Assert::fail('Сотрудник должен был быть удален');
            } catch (ApiException $e) {
                Assert::assertEquals(404, $e->getCode());
            }
        }
    }

    /**
     * Тест массового создания сотрудников с дублирующимися email
     */
    public function testBatchCreateEmployeesWithError(): void
    {
        $prefix = StringUtil::randomUuid();
        $employees = [];

         $employee = new Employee();
        $employee->setFirstName("Имя1");
        $employee->setLastName("$prefix Duplicate Employee");
        $employee->setPosition("Должность 1");
        $employee->setPhone("+79991234401");
        $employees[] = $employee;
        for ($i = 2; $i <= 3; $i++) {
            $employee = new Employee();
            $employee->setFirstName("Имя$i");
            $employee->setLastName("$prefix Duplicate Employee");
            $employee->setPosition(true);
            $employee->setPhone("+79991234" . (400 + $i));
            $employees[] = $employee;
        }

        try {
            $res = EmployeesApiTest::$api->entityEmployeeBatchPost($employees);
        } catch (ApiException $e) {
            $res = json_decode($e->getResponseBody(), true);
        }

        $success = 0;
        $errors = 0;
        foreach ($res as $item) {
            if (isset($item['errors'])) {
                $errors++;
            } else {
                $success++;
            }
        }

        Assert::assertGreaterThanOrEqual(1, $success, 'Ожидается как минимум 1 успешное создание');
        Assert::assertGreaterThanOrEqual(1, $errors, 'Ожидается как минимум 1 ошибка');
    }

    /**
     * Тест массового удаления сотрудников с некорректными мета-данными
     */
    public function testBatchDeleteEmployeesWithError(): void
    {
        $prefix = StringUtil::randomUuid();

        $employee = new Employee();
        $employee->setFirstName("Тест");
        $employee->setLastName("$prefix Delete Employee");
        $employee->setPosition("Тестовая должность");
        $employee->setPhone("+79991234567");

        $response = EmployeesApiTest::$api->entityEmployeePost($employee);

        $metaArray = [];

        $meta1 = new Employee();
        $meta1->setMeta($response->getMeta());
        $metaArray[] = $meta1;

        // Мета-данные с некорректным ID
        $meta2 = new Employee();
        $metaInvalidId = clone $response->getMeta();
        $newHref = preg_replace(
            '/[0-9a-fA-F-]{36}/',
            'invalid-uuid',
            $metaInvalidId->getHref()
        );
        $metaInvalidId->setHref($newHref);

        $meta2->setMeta($metaInvalidId);
        $metaArray[] = $meta2;

        // Мета-данные с некорректным типом
        $meta3 = new Employee();
        $metaInvalidType = clone $response->getMeta();
        $newHref2 = str_replace('/employee/', '/counterparty/', $metaInvalidType->getHref());
        $newHref2 = preg_replace(
            '/[0-9a-fA-F-]{36}/',
            'invalid-uuid',
            $newHref2
        );
        $metaInvalidType->setHref($newHref2);
        $meta3->setMeta($metaInvalidType);
        $metaArray[] = $meta3;

        try {
            $res = EmployeesApiTest::$api->entityEmployeeDeletePost($metaArray);
            Assert::fail('Ожидалось исключение ApiException из-за некорректных мета-данных');
        } catch (ApiException $e) {
            $res = json_decode($e->getResponseBody(), true);
        }

        $success = 0;
        $errors = 0;
        foreach ($res as $item) {
            if (isset($item['errors'])) {
                $errors++;
            } else {
                $success++;
                Asserter::assertStringContainsString('удален', $item['info']);
            }
        }

        Assert::assertSame(1, $success, 'Ожидается 1 успешное удаление');
        Assert::assertSame(2, $errors, 'Ожидается 2 ошибки');
    }

    /**
     * Тест массового удаления сотрудников с пустым массивом
     */
    public function testBatchDeleteEmployeesWithEmptyArray(): void
    {
        try {
            EmployeesApiTest::$api->entityEmployeeDeletePost([]);
            Assert::fail('Ожидалось исключение InvalidArgumentException для пустого массива');
        } catch (\InvalidArgumentException $e) {
            Asserter::assertStringContainsString('Missing the required parameter', $e->getMessage());
        }
    }
}